<script type="text/javascript">
    $(document).ready(function(){
        $("#nome").keyup(function(ev) {
                var nome = $('#nome').val();
                var url = '/sistema/recibo/pesquisa/nome/'+nome;
                $.ajax({
                    type: "POST",
                    url: url,
                    data: {nome:nome},
                    dataType: "html",
                    success: function(data){
                       $("#load_protesto").html(data);
                    }
                });
        });
        $("#btn_limpa").click(function(){
            $('#nome').val('');
            var nome = ' ';
            var url = '/sistema/recibo/pesquisa/nome/'+nome;
           $.ajax({
                type: "POST",
                url: url,
                data: {nome:nome},
                dataType: "html",
                success: function(data){
                   $("#load_protesto").html(data);
                }
            });
        });
        
        $("#modal_btn_protesto").click(function(event) {
            event.preventDefault();
            var radio_item = $(".modal_id_protesto:checked");
            if (radio_item && radio_item.length) {
                $("#id_protesto").val(radio_item.val());
                $("#show_id_protesto").val(radio_item.attr("title"));
                $("#myModal").modal("hide");
            } else {
                alert('não marcou ninguém!');
            }
        });    
        
    });
</script>
<form method="post" action="/sistema/recibo/inserir/" class="form-horizontal" name="form1"  enctype="multipart/form-data" id="form1" runat="server">
<div class="row">
    <section class="col-md-12">
    <div class="nav-tabs-custom">
        <!-- Tabs within a box -->
        <ul class="nav nav-tabs ui-sortable-handle">
          <li class="active"><a href="#user" data-toggle="tab">Recibo</a></li>
          <a style="margin: 5px" class="btn btn-default pull-right"  data-toggle="tooltip" href="/sistema/recibo/index/" title="Voltar"><i class="fa fa-reply"></i></a>
          <button style="margin: 5px" data-toggle="tooltip" type="submit" class="btn btn-primary pull-right" title="Salvar"><i class="fa fa-save"></i></button>
          <button style="margin: 5px" data-toggle="tooltip" type="reset" class="btn btn-danger pull-right" title="Limpar"><i class="fa fa-trash-o"></i></button>
        </ul>
    </div>
        <div class="tab-content no-padding">
            <div class="tab-pane active" id="user">
                <div class="box box-info">
            <div class="box-header ui-sortable-handle" >
              <i class="fa fa-list"></i>
              <h3 class="box-title"></h3>
              <!-- tools box -->
              <div class="pull-right box-tools">
                
              </div><!-- /. tools -->
            </div>
            <div class="box-body">
                <div class="form-group " id="ftipo">
                  <label for="id_pessoa" class="col-sm-3 control-label">Adicionar Protesto:</label>
                  <div class="col-sm-6">
                    <div class="input-group input-group-sm">
                        <input type="hidden" name="id_protesto"/>
                        <input type="text" class="form-control" id="show_id_protesto" disabled="">
                        <span class="input-group-btn">
                          <a href="#myModal" role="button" class="btn btn-info" data-toggle="modal"><i class="fa fa-plus-square-o"></i></a>
                        </span>
                    </div>
                  </div>
                </div>
                <div class="form-group">
                  <label class="col-sm-3 control-label">Taxa:</label>
                    <div class="col-sm-6">
                        <select class="form-control" name="id_taxas">
                            <?php foreach ($view_txs as $tx){ ?>
                            <option value="<?php echo $tx['id_taxas'];?>" <?php ($tx['id_taxas'] && $tx['id_taxas'] == 3) ? print "selected" : print ""; ?>><?php echo $tx['descricao'];?></option>
                            <?php } ?>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label for="valor" class="col-sm-3 control-label">Valor:</label>
                    <div class="col-sm-6">
                        <input type="text" class="form-control moeda" name="valor" id="valor" value="" placeholder="0,00">
                    </div>
                </div>
                <div class="form-group">
                  <label class="col-sm-3 control-label">Descrição:</label>
                  <div class="col-sm-6">
                      <textarea name="descricao" class="form-control" rows="3" placeholder=""></textarea>
                  </div>
                </div>
            </div>
            </div>
            </div>            
        </div>
    </section>
</div>
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Protestos</h3>
  </div>
  <div class="modal-body">
      <div class="form-group">
        <label for="login" class="col-sm-3 control-label">Responsável:</label>
        <div class="col-sm-6">
          <div class="input-group input-group-sm">
              <input type="hidden" name="id_protesto" id="id_protesto"/>
              <input type="text" class="form-control" id="nome" type="text" placeholder="Digite um nome...">
              <span class="input-group-btn">
                <button class="btn btn-danger" id="btn_limpa" type="button"><i class="fa fa-trash-o"></i></button>
              </span>
          </div>
        </div>
        </div>
        <table class="table table-bordered">
            <tr class="titulo2">
                <th></th>
                <th>ID</th>
                <th>Responsável</th>
                <th>Aluno</th>
                <th>Emissão</th>
                <th>Vencimento</th>
            </tr>
            <tbody id="load_protesto">
            <?php foreach ($view_prot as $prot){
                $respon = new ResponsavelModel($prot['id_responsavel']);
                $aluno = new AlunoModel($prot['id_aluno']);
                $p_resp = new PessoaModel($respon->id_pessoa);
                $a_resp = new PessoaModel($aluno->id_pessoa);
                $txt_emissao = UtilHelper::formatBr($prot['data_emissao']);
                $txt_vencimento = UtilHelper::formatBr($prot['data_vencimento']);
            ?>
            <tr>
                <td><input type="radio" value="<?php echo $prot["id_protesto"]; ?>" name="id_protesto" class="modal_id_protesto" title="<?php echo $p_resp->nome;?>"  /></td>
                <td><span class="badge badge-inverse"><?php echo $prot["id_protesto"]; ?></span></td>
                <td><?php echo $p_resp->nome; ?></td>
                <td><?php echo $a_resp->nome; ?></td>
                <td><?php echo $txt_emissao; ?></td>
                <td><?php echo $txt_vencimento; ?></td>
            </tr>
            <?php }?>
            </tbody>
        </table>
  </div>
  <div class="modal-footer">
    <button class="btn btn-danger" data-dismiss="modal" aria-hidden="true">Cancelar</button>
    <button class="btn btn-primary" id="modal_btn_protesto">Salvar</button>
  </div>
</div>
</div>
</div>
</form>