<div class="row">
    <section class="col-md-12">
        <div class="box box-info">
            <div class="box-header ui-sortable-handle" >
              <i class="fa fa-list"></i>
              <h3 class="box-title">Vagas</h3>
              <!-- tools box -->
              <div class="pull-right box-tools">
                    <a class="btn btn-default pesquisar" href="#" title="Pesquisar" data-toggle="tooltip"><i class="fa fa-search"></i></a>
                    <a class="btn btn-default" href="/sistema/index/index/" data-toggle="tooltip" title="Voltar"> <i class="fa fa-reply"></i></a>
                    <a class="btn btn-default" href="/sistema/matricula/selecioneano/" data-toggle="tooltip" title="Trocar ano"> <i class="fa fa-exchange"></i></a>
              </div>
            </div>
            <div class="box-body">
                <div class="col-md-4 well-sm areapesquisa" style="display: none">
            <form class="form-horizontal" action="/sistema/matricula/index/" method="post">
                <div class="input-group input-group-sm">
                    <input type="text" class="form-control" name="nome"placeholder="Buscar Nome...">
                    <span class="input-group-btn">
                      <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i> Buscar</button>
                      <a class="btn btn-danger" href="/sistema/matricula/index/" title=""><i class="fa fa-close"></i> Limpar Busca</a>
                    </span>
                </div>
            </form>
            </div>
                <table class="table table-condensed">
                <thead>
                    
                <tr>
                  <th style="width: 100px; text-align: center">Turma</th>
                  <th><center>Progresso</center></th>
                  <th style="width: 200px; text-align: center">Vagas Disponíveis</th>
                  <th style="width: 50px; text-align: center"></th>
                </tr>
                </thead>
        <?php if($view_turma){  ?>
                <tbody>
                
                <?php foreach ($view_turma as $turma){
                    $mat = new MatriculaModel();
                    $listMat = $mat->listarPorTurmaAtivos($turma['id_turma']);
                    $count_vaga  = count($listMat);
                    $txt_vaga = $turma['vagas'] - $count_vaga;
                    $porcent = 0;
                    $bg ='';
                    $pg ='';
                    if($count_vaga){
                        $porcent = $count_vaga * 100 / $turma['vagas'];
                    }
                    if($porcent <= 70){
                        $bg = 'bg-green';
                        $pg = 'progress-bar-success';
                    }
                    if($porcent > 70 && $porcent <= 99){
                        $bg = 'bg-yellow';
                        $pg = 'progress-bar-warning';
                    }
                    if($porcent == 100){
                        $bg = 'bg-red';
                        $pg = 'progress-bar-danger';
                    }
                    if($porcent > 100){
                        $bg = 'bg-blue';
                        $pg = 'progress-bar-primary';
                    }
                ?>
                <tr>
                  <td align='center'><span class="badge <?php echo $bg; ?>"><?php echo $turma['descricao']; ?></span></td>
                  <td align='center'>
                    <div class="progress progress-xs">
                        <div class="progress-bar <?php echo $pg; ?>" style="width: <?php echo $porcent; ?>%"></div>
                    </div>
                  </td>
                  <td align='center'><span class="badge <?php echo $bg; ?>"><?php echo $txt_vaga; ?></span></td>
                  <td>
                    <div class="btn-group">
                        <button type="button" class="btn btn-info btn-sm dropdown-toggle" data-toggle="dropdown">
                          <i class="fa fa-bars"></i></button>
                        <ul class="dropdown-menu pull-right" role="menu">
<!-- 
                          <li><a href="#" data-toggle="modal" data-target="#matricula<?php echo $turma['id_turma'];?>"><i class="fa fa-plus-square-o"></i> Matricula</a></li>
                          <li><a href="#" data-toggle="modal" data-target="#rematricula<?php echo $turma['id_turma'];?>"><i class="fa fa-plus-square"></i> Rematricula</a></li>
                          <li class="divider"></li>                         
                          <li><a href="#" data-toggle="modal" data-target="#reserva<?php echo $turma['id_turma'];?>"><i class="fa fa-calendar"></i> Reserva</a></li>
                          <li class="divider"></li>
-->  
                          <li><a href="#" data-toggle="modal" data-target="#alunosturma<?php echo $turma['id_turma'];?>"><i class="fa fa-users"></i> Alunos na Turma</a></li>
                          <li><a href="#" data-toggle="modal" data-target="#devolucao<?php echo $turma['id_turma'];?>"><i class="fa fa-refresh"></i> Devolução Aluno</a></li>
                          <li><a href="#" data-toggle="modal" data-target="#alunos<?php echo $turma['id_turma'];?>"><i class="fa fa-graduation-cap"></i> Alunos Reservados</a></li>
                          <li class="divider"></li>
                          <li><a href="#" data-toggle="modal" data-target="#troca<?php echo $turma['id_turma'];?>"><i class="fa fa-refresh"></i> Troca de Turma</a></li>
</ul>
                    </div>
                  </td>
                </tr>
                <?php } ?>
                </tbody>
                <?php } else { ?>
                <tfoot>
                    <tr>
                        <td colspan="6">
                            Não existe turma cadastrada neste ano!
                        </td>
                    </tr>
                </tfoot>
                <?php } ?>
                </table>
            
            </div>
        </div>
        </section>
</div>
<?php foreach ($view_sql as $sql){ ?>
<div class="modal fade" id="id<?php echo "{$sql["id_ano"]}";?>" tabindex="-1" role="dialog" aria-labelledby="id<?php echo "{$sql["id_ano"]}";?>">
  <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          <h3 id="myModalLabel">Deseja Realmente Apagar esta Taxa?</h3>
        </div>
        <div class="modal-body">
            <p>O registro será apagado permanente!</p>
        </div>
        <div class="modal-footer">
            <a class="btn btn-danger" href="<?php echo "/sistema/ano/excluir/id/{$sql["id_ano"]}";?>" title="Excluir">Sim</a>
            <button class="btn btn-info" data-dismiss="modal" aria-hidden="true">Cancelar</button>
        </div>
    </div>
  </div>
</div>
<?php } ?>
<script type="text/javascript">

$(document).ready(function() {
  $(".nome").keyup(function(){
    $(this).val($(this).val().toUpperCase());
  });
  
  $('.matricula').keyup(function(){
    $(this).val($(this).val().replace(/[^\d]/,''));
  });
  $('.sele').click(function(){
      var valor = $(this).val();
      $('.matricula').attr('disabled', true);
      $('.mtr').attr('disabled', true);
      $('#mt'+valor).attr('disabled', false);
      $('#mtr'+valor).attr('disabled', false);
  });
});
</script>
<?php if($view_turma){  ?>
<?php 
date_default_timezone_set('America/Belem');
$date = date('Y-m-d H:i:s');
/*
 * DESATIVADO PORQUE ESSA FOI A PRIMEIRA SOLUÇÃO PARA INSERIR ALUNOS NO SISTEMA
 * FOI O PRIMEIRO METODO DE MATRICULA REMATRICULA E RESERVA
 * HOJE É TUDO FEITO PELA MATRICULA ESPERA
 * 
foreach ($view_turma as $turma){ 

?>
<div class="modal fade modal-primary" id="matricula<?php echo $turma['id_turma'];?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Matrícula - Turma <?php echo $turma['descricao'];?></h4>
      </div>
        <form method="post" action="/sistema/matricula/inserir">
            <input type="hidden" name="id_matricula_status" value="1" />
            <input type="hidden" name="id_turma" value="<?php echo $turma['id_turma'];?>" />
            <input type="hidden" name="id_usuario" value="<?php echo $_SESSION["userData"]["id_usuario"];?>" />
            <input type="hidden" name="data" value="<?php echo $date;?>" />
          <div class="modal-body">
            <div class="box-body">
                <div class="form-group col-md-4">
                  <label for="nome">Matrícula:</label>
                  <input type="text" name="matricula" class="form-control matricula"  id="matricula" placeholder="Número da matrícula">
                </div>
                <div class="form-group col-md-12">
                  <label for="nome">Nome do Aluno:</label>
                  <input type="text" name="nome" class="form-control nome" id="nome" placeholder="Nome completo">
                </div>
            </div>
          </div>
          <div class="modal-footer">
            <a href="/sistema/matricula/index" class="btn btn-default" ><i class="fa fa-close"></i></a>
            <button type="submit" class="btn btn-default"><i class="fa fa-save"></i></button>
          </div>
        </form>
    </div>
  </div>
</div>
<?php } ?>

<?php foreach ($view_turma as $turma){ ?>
<!-- Modal -->
<div class="modal fade modal-primary" id="rematricula<?php echo $turma['id_turma'];?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Rematricula - Turma <?php echo $turma['descricao'];?></h4>
      </div>
       <form method="post" action="/sistema/matricula/inserir">
            <input type="hidden" name="id_matricula_status" value="2" />
            <input type="hidden" name="id_turma" value="<?php echo $turma['id_turma'];?>" />
            <input type="hidden" name="id_usuario" value="<?php echo $_SESSION["userData"]["id_usuario"];?>" />
            <input type="hidden" name="data" value="<?php echo $date;?>" />
          <div class="modal-body">
            <div class="box-body">
                <div class="form-group col-md-4">
                  <label for="nome">Matrícula:</label>
                  <input type="text" name="matricula" class="form-control matricula"  id="matricula" placeholder="Número da matrícula">
                </div>
                <div class="form-group col-md-12">
                  <label for="nome">Nome do Aluno:</label>
                  <input type="text" name="nome" class="form-control nome" id="nome" placeholder="Nome completo">
                </div>
            </div>
          </div>
          <div class="modal-footer">
            <a href="/sistema/matricula/index" class="btn btn-default" ><i class="fa fa-close"></i></a>
            <button type="submit" class="btn btn-default"><i class="fa fa-save"></i></button>
          </div>
        </form>
    </div>
  </div>
</div>
<?php } ?>

<?php foreach ($view_turma as $turma){ ?>
<!-- Modal -->
<div class="modal fade modal-primary" id="reserva<?php echo $turma['id_turma'];?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog " role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Reserva - Turma <?php echo $turma['descricao'];?></h4>
      </div>
        <form  action="/sistema/matricula/inserir" method="POST">
            <input type="hidden" name="id_matricula_status" value="3" />
            <input type="hidden" name="id_turma" value="<?php echo $turma['id_turma'];?>" />
            <input type="hidden" name="id_usuario" value="<?php echo $_SESSION["userData"]["id_usuario"];?>" />
            <input type="hidden" name="data" value="<?php echo $date;?>" />
          <div class="modal-body">
            <div class="box-body">
                <div class="form-group col-md-4">
                  <label for="nome">Matrícula:</label>
                  <input type="text" name="matricula" class="form-control matricula"  placeholder="Número da matrícula">
                </div>
                <div class="form-group col-md-12">
                  <label for="nome">Nome do Aluno:</label>
                  <input type="text" name="nome" class="form-control nome" id="nome" placeholder="Nome completo">
                </div>
            </div>
          </div>
          <div class="modal-footer">
            <a href="/sistema/matricula/index" class="btn btn-default" ><i class="fa fa-close"></i></a>
            <button type="submit" class="btn btn-default"><i class="fa fa-save"></i></button>
          </div>
        </form>
    </div>
  </div>
</div>
<?php  } */ ?>

<?php foreach ($view_turma as $turma){
    $mtr = new MatriculaModel();
    $listMatri = $mtr->listarPorTurmaReserva($turma['id_turma']);
?>
<!-- Modal -->
<div class="modal fade modal-primary" id="alunos<?php echo $turma['id_turma'];?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog " role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Alunos Reservas - Turma <?php echo $turma['descricao'];?></h4>
        
      </div>
        <form  action="/sistema/matricula/matricular" method="POST">
            <table class="table table-striped">
                <tr>
                    <th style="width: 10px">#</th>
                    <th>Nome do Aluno</th>
                    <th>Número de Matrícula</th>
                    <th>Tipo</th>
                </tr>
                <?php
                if($listMatri){
                    
                foreach ($listMatri as $matri){ 
                    $malu = new MalunoModel($matri['id_m_aluno']);
                    $mst = new MatriculastatusModel($matri['id_matricula_status']);
                    $label = "";
                    if($mst->chave == "MT"){
                        $label = "label-success";
                    }
                    if($mst->chave == "RMT"){
                        $label = "label-info";
                    }
                    
                    if($mst->chave == "RV"){
                        $label = "label-warning";
                    }
                    $txt_matri = "<input id='mt{$matri['id_matricula']}' type='text' name='matricula' class='matricula form-control' placeholder='Nº de Matrícula' disabled />";
                    if($malu->matricula){
                        $txt_matri = $malu->matricula;
                    }
                ?>
                <tr>
                    <td>
                        <input class="sele" type="radio" name="id_matricula" value="<?php echo $matri['id_matricula'];?>" />
                    </td>
                    <td>
                        <?php echo $malu->nome; ?>
                        <input type="hidden" name="nome" id="mtr<?php echo $matri['id_matricula']; ?>" class="mtr" value="<?php echo $malu->nome; ?>" disabled />
                    </td>
                    <td><?php echo $txt_matri; ?></td>
                    <td><span class="label <?php echo $label; ?> "><?php echo $mst->descricao; ?></span></td>
                </tr>
                <?php }} else { ?>
                <tr>
                    <td colspan="4" class="bg-yellow">
                        Não existe aluno reservado nesta turma.
                    </td>
                </tr>
                <?php } ?>
            </table>
            <div class="modal-footer">
            <a href="/sistema/matricula/index" class="btn btn-default" ><i class="fa fa-close"></i></a>
            <button type="submit" name="rematricular" class="btn btn-default"> Rematricular</button>
            <button type="submit" name="matricular" class="btn btn-default"> Matricular</button>
          </div>
        </form>
    </div>
  </div>
</div>
<?php } ?>
<script type="text/javascript">
$(document).ready(function(){
    $('.sele_turm').change(function(){
        var id_turma = $(this).val();
        if(id_turma){
            var url = '/sistema/matriculaespera/buscarturma/id/'+id_turma;
            $.ajax({
                type: "POST",
                url: url,
                data: {id:id_turma},
                dataType: "html",
                success: function(data){
                   $(".list_alun").html(data);
                }
            });
        }
    });
    
    $('.list_alun').change(function(){
        var list_alun = $(this).val();
        if(list_alun){
            var url = '/sistema/matricula/buscarmatricula/id/'+list_alun;
            $.ajax({
                type: "POST",
                url: url,
                data: {id:list_alun},
                dataType: "html",
                success: function(data){
                   $(".list_imput").html(data);
                }
            });
        }
    });
});
</script>
<?php foreach ($view_turma as $turma){ ?>
<div class="modal fade" id="troca<?php echo $turma['id_turma'];?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header bg-green">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Troca de aluno para turma - <?php echo $turma['descricao'];?></h4>
      </div>
<form method="post" action="/sistema/matricula/editartroca/">
    
          <div class="modal-body">
              <?php $matriculas = new MatriculaModel();
              $listat = $matriculas->listarPorTurmaAtivos($turma['id_turma']);
              
              $cl = count($listat);
              
              if($cl == $turma['vagas']){  ?>
            <table class="table table-condensed">
                <tr>
                    <td class="bg-yellow">Não existe vagas disponíveis nesta turma!</td>
                </tr>
            </table>
               <?php } else { ?>
              <div class="list_imput"></div>
              <div class="row">
                  <div class="col-md-2">
                    <div class="form-group">
                        <label>Turma Anterior:</label>
                        <select class="form-control sele_turm">
                            <option value=""> Selecione </option>
                            <?php foreach($view_turma as $trm){ ?>
                            <option value="<?php echo $trm['id_turma'];?>"><?php echo $trm['descricao'];?></option>
                            <?php } ?>
                        </select>
                    </div>
                  </div>
                  <div class="col-md-4">
                    <div class="form-group">
                      <label>Aluno:</label>
                      <select class="form-control list_alun" name="id_matricula">
                          <option value="">Selecione</option>
                      </select>
                    </div>
                  </div>
              </div>
            <input type="hidden" name='id_turma' value="<?php echo $turma['id_turma']?>" />
               <?php }  ?>
          </div>
          <div class="modal-footer">
            <a href="/sistema/matricula/index" class="btn btn-default" ><i class="fa fa-close"></i></a>
            <button type="submit" class="btn btn-default"><i class="fa fa-save"></i></button>
          </div>
        </form>
    </div>
  </div>
</div>    


<div class="modal fade" id="devolucao<?php echo "{$turma['id_turma']}";?>" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content">
        <div class="modal-header bg-green">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          <h4 class="modal-title"  id="myModalLabel">Alunos Desativados</h4>
        </div>
        <div class="modal-body">
            <table class="table table-striped table-condensed">
                <tr>
                    <th>Nome do aluno</th>
                    <th class="text-center">Matrícula</th>
                    <th class="text-center">Tipo</th>
                    <th class="text-right"><i class="fa fa-cog" style="margin-right: 10px"></i></th>
                </tr>
                <?php 
                $color = array(
                        1 => "info",
                        2 => "success",
                        3 => "warning"
                    );
                $listdstv = $matriculas->listarPorTurmaDesativados($turma['id_turma']);
                foreach ($listdstv as $entity){
                    
                        $m_aluno = new MalunoModel($entity['id_m_aluno']);
                        $usu = new UsuarioModel($entity['id_usuario']);
                        $mts = new MatriculastatusModel($entity['id_matricula_status']);
                ?>
                <tr>
                    <td><?php echo $m_aluno->nome; ?></td>
                    <td class="text-center"><?php echo $m_aluno->matricula; ?></td>
                    <td class="text-center"><span class="label label-<?= $color[$mts->id_matricula_status]; ?>"><?php echo $mts->descricao; ?></span></td>
                    <td class="text-right"> <a href="<?php echo "/sistema/matricula/devolucao/id/{$entity["id_matricula"]}";?>" data-toggle="tooltip" data-title="Ativar" class="btn btn-default btn-sm"> <i class="fa fa-upload"></i></a></td>
                </tr>
                <?php } ?>
            </table>
        </div>
        <div class="modal-footer">
            <button class="btn btn-info" data-dismiss="modal" aria-hidden="true">Cancelar</button>
        </div>
    </div>
  </div>
</div>


<div class="modal fade" id="alunosturma<?php echo "{$turma['id_turma']}";?>" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content">
        <div class="modal-header bg-green">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          <h4 class="modal-title"  id="myModalLabel"><i class="fa fa-users"></i> Alunos na Turma</h4>
        </div>
        <div class="modal-body">
            <script type="text/javascript">
                    $(document).ready(function() 
                        { 
                            $("#tbaluno<?php echo "{$turma['id_turma']}";?>").tablesorter(); 
                        } 
                    ); 
            </script>
            <table id="tbaluno<?php echo "{$turma['id_turma']}";?>" class="tablesorter table  table-bordered ">
                <thead>
                    <tr>
                        <th><i class="fa fa-arrows-v"></i> ID</th>
                        <th>Nome do aluno</th>
                        <th>Matrícula</th>
                        <th>Tipo</th>
                        <th>Usuário</th>
                        <th>Data e hora</th>
                    </tr>
                </thead>
                <tbody>
                <?php 
                $cont_aluno = 0;
                foreach ($listat as $entity){
                    $cont_aluno++;
                        $m_aluno = new MalunoModel($entity['id_m_aluno']);
                        $usu = new UsuarioModel($entity['id_usuario']);
                        $pes = new PessoaModel($usu->id_pessoa);
                        $mts = new MatriculastatusModel($entity['id_matricula_status']);
                        $date = new DateTime($entity['data_cadastro']);
                ?>
                <tr>
                    <td><?php echo $cont_aluno; ?></td>
                    <td><?php echo $m_aluno->nome; ?></td>
                    <td><?php echo $m_aluno->matricula; ?></td>
                    <td class="text-center"><span class="label label-<?= $color[$mts->id_matricula_status]; ?>"><?php echo $mts->descricao; ?></span></td>
                    <td><?php echo $pes->nome; ?></td>
                    <td><?php echo $date->format('d-m-Y H:i:s'); ?></td>
                </tr>
                <?php } ?>
                </tbody>
            </table>
        </div>
        <div class="modal-footer">
            <button class="btn btn-info" data-dismiss="modal" aria-hidden="true">Cancelar</button>
        </div>
    </div>
  </div>
</div>



<?php } ?>
<?php } ?>