<?php 
    $aluno = new MalunoModel($view_sql['id_m_aluno']);
    $visi = new VisitanteModel($view_sql['id_visitante']);
    $txt_data_nasc = "";
    if($aluno->data_nascimento){
        $txt_data_nasc = UtilHelper::formatBr($aluno->data_nascimento);
    }
?>
<script type="text/javascript">

$(document).ready(function() {
  $(".ip").keyup(function(){
    $(this).val($(this).val().toUpperCase());
  });
});
</script>
<form method="post" action="/sistema/matriculaespera/editartroca/id/<?php echo $view_sql['id_matricula_espera']; ?>"  name="form1"  enctype="multipart/form-data" id="form1" runat="server">
    <input type="hidden" name="id_matricula_espera" value="<?php echo $view_sql['id_matricula_espera']; ?>"/>
    <input type="hidden" name="id_m_aluno" value="<?php echo $view_sql['id_m_aluno']; ?>"/>
    <input type="hidden" name="id_turma" value="<?php echo $view_sql['id_turma']; ?>"/>
    <input type="hidden" name="id_usuario" value="<?php echo $view_sql['id_usuario']; ?>"/>
    <input type="hidden" name="status" value="<?php echo $view_sql['status']; ?>"/>
    <input type="hidden" name="data" value="<?php echo $view_sql['data_cadastro']; ?>"/>
    <input type="hidden" name="id_visitante" value="<?php echo $view_sql['id_visitante']; ?>"/>
    <input type="hidden" name="troca" value="S"/>
    
    <div class="row">
    <section class="col-md-12">
    <div class="nav-tabs-custom">
        <!-- Tabs within a box -->
        <ul class="nav nav-tabs ui-sortable-handle">
          <li class="active"><a href="#prot" data-toggle="tab">Editar Aluno</a></li>
          <a style="margin: 5px" class="btn btn-default pull-right" href="/sistema/matriculaespera/turma/id/<?php echo $view_sql['id_turma']; ?>"data-toggle="tooltip" title="Voltar"><i class="fa fa-reply"></i></a>
          <button style="margin: 5px" type="submit" class="btn btn-primary pull-right" data-toggle="tooltip" title="Salvar"><i class="fa fa-save"></i></button>
          <button style="margin: 5px" type="reset" class="btn btn-danger pull-right" data-toggle="tooltip" title="Limpar"><i class="fa fa-trash-o"></i></button>
        </ul>
    </div>
        <div class="tab-content no-padding">
            <div class="tab-pane active" id="prot">
        
                <div class="box box-info">
                    <div class="box-header ui-sortable-handle" >
                      <i class="fa fa-envelope"></i>
                      <h3 class="box-title">Editar Visitante</h3>
                      <!-- tools box -->
                      <div class="pull-right box-tools">
                        
                      </div><!-- /. tools -->
                    </div>
                    <div class="box-body">

    <div class="col-md-4">
        <div class="form-group">
            <label>Nome do Aluno:</label>
            <input type="text" value="<?php echo $aluno->nome;?>" class="form-control"  disabled="">
            <input type="hidden" name="nome" value="<?php echo $aluno->nome;?>">
            <input type="hidden" name="data_nascimento" value="<?php echo $txt_data_nasc;?>">
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group">
            <label>Visitante:</label>
            <input type="text" value="<?php echo $visi->nome; ?>" name="nome_visitante" class="form-control ip" placeholder="Nome completo">
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group">
          <label>Grau Parentesco:</label>
          <select class="form-control" name="grau_parentesco">
          <option value="">Selecione</option>
          <?php
          $listParente = UtilHelper::listaParentes();
          foreach ($listParente as $lp) { ?>
          <option value="<?php echo $lp;?>" <?php ($visi->grau_parentesco == $lp) ? print "selected" : print ""; ?>><?php echo $lp;?></option>
          <?php } ?>
          </select>
        </div>
    </div>
     
    <div class="col-md-6">
        <div class="form-group">
            <label>Email:</label>
            <input type="text" name="email" id="email" value="<?php echo $visi->email;?>"  class="form-control" placeholder="email@email.com">
        </div>
    </div>

    <div class="col-md-2">
        <div class="form-group">
            <label>Telefone:</label>
            <input type="text" value="<?php echo $visi->telefone;?>"  name="telefone" class="form-control telefone" placeholder="(__) ____-____">
        </div>
    </div>
    <div class="col-md-2">
        <div class="form-group">
            <label>Celular 1:</label>
            <input type="text" name="celular1" value="<?php echo $visi->celular1;?>"  class="form-control celular" placeholder="(__) _____-____">
        </div>
    </div>
    <div class="col-md-2">
        <div class="form-group">
            <label>Celular 2:</label>
            <input type="text" name="celular2" value="<?php echo $visi->celular2;?>"  class="form-control celular" placeholder="(__) _____-____">
        </div>
    </div>
        <div class="col-md-12">
          <div class="form-group">
              <label>Observação:</label>
              <textarea name="obs" class="form-control" rows="3" placeholder="..."></textarea>
          </div>
        </div>         
                
                </div>
            </div>
        </div>
            </section>
    </div>
    
</form>
