<script type="text/javascript">
$(document).ready(function(){
    $('#ano_de').change(function(){
        $("#load_turma_de").empty();
        var id = $(this).val();
        $("#load_turma_para").empty();
        if(id){
            var url = '/sistema/fichamento/turmasde/id/'+id;
            $.ajax({
                type: "POST",
                url: url,
                data: {id:id},
                dataType: "html",
                success: function(data){
                   $("#load_turma_de").html(data);
                }
            });
        }
        
        
    });
    
    $('#ano_para').change(function(){
        $("#load_turma_para").empty();
        var anode = $('#ano_de').val();
        var nomede = $('#ano_de option:selected').text();
        var anook = parseInt(nomede) + 1;
        var id = $(this).val();
        var nomeid = $('#ano_para option:selected').text();
        if(anode){
            if(anook == nomeid){
                var url = '/sistema/fichamento/turmaspara/id/'+id;
                $.ajax({
                    type: "POST",
                    url: url,
                    data: {id:id},
                    dataType: "html",
                    success: function(data){
                       $("#load_turma_para").html(data);
                    }
                });
            }else{
                $("#msg_alert").empty();
                $('<div class="alert alert-warning alert-dismissible" role="alert"> \n\
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">\n\
                    <span aria-hidden="true">×</span></button> \n\
                    <strong><i class="fa fa-warning"></i></strong> Você só pode fichar para o ano ' + anook + '! \n\
                </div>').appendTo('#msg_alert').fadeIn( 300 ).delay( 1500 ).fadeOut( 400 );
                $("#load_turma_para").empty();
                return false;
            }
        }else{
            $("#msg_alert").empty();
            $('<div class="alert alert-warning alert-dismissible" role="alert"> \n\
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">\n\
                    <span aria-hidden="true">×</span></button> \n\
                    <strong><i class="fa fa-warning"></i></strong> Selecione o ano atual ! \n\
                </div>').appendTo('#msg_alert').fadeIn( 300 ).delay( 1500 ).fadeOut( 400 );
            $("#load_turma_para").empty();
            return false;
        }
    });
    
    
    
});
</script>
<div class="box box-primary">
    <div class="box-header ui-sortable-handle">
        <i class="fa fa-clipboard"></i>
        <h3 class="box-title">Fichamento</h3>
    </div>
    <form method="post" action="">
    <div class="box-body">
        <div class="row">
            <div class="col-md-6">
                <div class="col-md-6">
                    <div class="form-group">
                        <label>Ano Anterior</label>
                        <select class="form-control" id="ano_de">
                            <option value="">Selecione</option>
                            <?php foreach ($view_ano as $ano) { ?>
                            <option value="<?= $ano['id_ano'];?>"><?= $ano['descricao'];?></option>
                            <?php } ?>
                        </select>
                    </div>
                    <ul class="todo-list ui-sortable" id="load_turma_de"></ul>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label>Ano Atual</label>
                        <select class="form-control" id="ano_para">
                          <option value="">Selecione</option>
                            <?php foreach ($view_ano as $ano) { ?>
                            <option value="<?= $ano['id_ano'];?>"><?= $ano['descricao'];?></option>
                            <?php } ?>
                        </select>
                    </div>
                    <ul class="todo-list ui-sortable" id="load_turma_para"></ul>
                </div>
            </div>
        </div>
    </div>
    <div class="box-footer clearfix no-border">
        <button type="submit" class="btn btn-primary pull-right"><i class="fa fa-save"></i> Salvar</button>
    </div>
    </form>
</div>