<form method="post" action="/sistema/estado/inserir/" class="form-horizontal">
<div class="well">
    <div class="navbar">
        <div class="span4"><h4>Pais - <a href="/sistema/estado/inserir/">Cadastro</a></h4></div>
        <div class="navbar-inner pull-right">
           
            <button type="submit" class="btn btn-primary">Salvar <i class="fa fa-save"></i></button>
            <button type="reset" class="btn btn-danger">Limpar <i class="fa fa-trash-o"></i></button>
            <a class="btn" href="/sistema/estado/index/" title="Voltar"> Voltar <i class="fa fa-reply"></i></a>
         
        </div>
    </div>
    <br /><hr />
        <div class="control-group">
        <label for="pais" class="control-label">Pais:</label>
        <div class="controls">
            <select name="id_pais" id="cur">
                    <option value="">=> Selecione <=</option>
                <?php foreach ($view_pais as $pais){ ?>
                    <option value="<?php echo $pais["id_pais"]; ?>"><?php echo $pais["nome"]; ?></option>
                <?php } ?>
            </select>
        </div>
        </div>
        <div class="control-group">
            <label for="nome" class="control-label">Estado:</label>
            <div class="controls">
                <input type="text" name="nome" id="nome" value="" class="span2" />
            </div>
        </div>
        <div class="control-group">
            <label for="sigla" class="control-label">Sigla:</label>
            <div class="controls">
                <input type="text" name="sigla" id="sigla" value="" class="span2" />
            </div>
        </div>
        
</div>
</form>