<form method="post" action="/sistema/grupo/inserir/" class="form-horizontal">
<div class="row">
    <section class="col-md-12">
    <div class="nav-tabs-custom">
        <!-- Tabs within a box -->
        <ul class="nav nav-tabs ui-sortable-handle">
          <li id="ab1" class="active"><a href="#aba1" data-toggle="tab">Inserir Responsável</a></li>
          <a style="margin: 5px" class="btn btn-default pull-right" href="/sistema/grupo/index/"data-toggle="tooltip" title="Voltar"><i class="fa fa-reply"></i></a>
          <button style="margin: 5px" type="submit" class="btn btn-primary pull-right" data-toggle="tooltip" title="Salvar"><i class="fa fa-save"></i></button>
          
        </ul>
    </div>
    <div class="tab-content no-padding">
        <div class="tab-pane active" id="aba1">
        <div class="box box-info">
            <div class="box-header with-border">
              <h3 class="box-title">Inserir</h3>
            </div>
            <div class="box-body">
                <div class="form-group">
                    <label for="nome" class="control-label col-sm-3">Nome:</label>
                    <div class="col-sm-6">
                        <input type="text" name="nome" id="nome" size="5" value="" class="form-control" />
                    </div>
                </div>
                <div class="form-group">
                  <div class="col-sm-offset-3 col-sm-10">
                    <div class="checkbox">
                      <label>
                        <input type="checkbox" name="padrao" id="padrao"  size="5" value="S"> Grupo padrão
                      </label>
                    </div>
                  </div>
                </div>
            </div>
        </div>
        </div>   
    </div>
    </section>
</div>
</form>

