<div class="well">
<div class="navbar">
    <div class="span4"><h4>Bairro - <a href="/sistema/bairro/">Listar</a></h4></div>
    <div class="navbar-inner pull-right">
        <div class="">
        <a class="btn" href="/sistema/bairro/inserir/" title="Adicionar">Adicionar <i class="icon-plus-sign"></i></a>
        <a class="btn" href="/sistema/index/index/" title="Voltar"> Voltar <i class="icon-circle-arrow-left"></i></a>
    </div>
    </div>
</div>
    <br />
    <hr />
    <table class="table table-bordered">
        <tr>
            <th colspan="7" class="titulo2">Bairros</th>
        </tr>
        <tbody>
            <tr class="itemTitulo2">
                <td>Municipio</td>
                <td>Bairro</td>
                <td>Operações</td>
            </tr>
            <?php 
                foreach ($view_sql as $sql){
                    $mu = new MunicipioModel($sql['id_municipio']);
            ?>
            <tr>
                <td><strong><?php echo $mu->nome; ?></strong></td>
                <td><?php echo $sql['nome'];?></td>
                <td>
                    <div class="btn-group">
                        <a class="btn btn-success" href="<?php echo "/sistema/bairro/visualizar/id/{$sql["id_bairro"]}";?>" title="Visualizar"><i class="fa fa-search"></i></a>
                        <a class="btn btn-warning" href="<?php echo "/sistema/bairro/editar/id/{$sql["id_bairro"]}";?>" title="Editar"><i class="fa fa-edit"></i></a>
                        <a class="btn btn-danger" href="<?php echo "/sistema/bairro/excluir/id/{$sql["id_bairro"]}";?>" title="Excluir"><i class="fa fa-trash-o"></i></a>
                    </div>
                </td>
            </tr>
            <?php } ?>
            
    </tbody>
</table>
<?php
if($view_numero){
        $sis = new System();
?>
    <center>
    <div class="pagination">
            <ul>
<?php
    $nun = $sis->getParam('page');
    if(!$nun){
        $nun = 1;
    }
    $avan = $nun +1;
    $volt = $nun -1;
    if($avan > $view_numero){
        $avan = $view_numero;
    }
    if($volt < 1){
        $volt = 1;
    }
    if($nun > 1){
?>
                <li><a href="/sistema/bairro/index/page/<?php echo $volt; ?>"><i class="fa fa-arrow-circle-o-left"></i></a></li>
<?php
    }
    
    for($i = 1; $i < $view_numero + 1; $i++) { 
        $active = "";
        if($nun == $i){
            $active = "active";
        }
        echo   "<li class='$active' ><a href='/sistema/bairro/index/page/$i'>$i</a></li>";
    }
    if($nun < $view_numero){
?>
                <li><a href="/sistema/bairro/index/page/<?php echo $avan; ?>"><i class="fa fa-arrow-circle-o-right"></i></a></li>
<?php } ?>        
            </ul>
        </div>
        </center>
<?php } ?>
</div>