<div class="row">
    <div class="span10">            
        <ul class="breadcrumb">
            <li><a href="/sistema/index/index/"><i class="fa fa-home"></i> Início</a> <span class="divider">/</span></li>
            <li><a href="/sistema/bairro/index/"><i class="fa fa-cog"></i>Bairro</a> <span class="divider">/</span></li>
            <li class="active">Visualizar</li>
        </ul>
    </div>
    <div class="span3">
        
        <a class="btn" href="/sistema/bairro/index/" title="Voltar"> Voltar <i class="fa fa-reply"></i></a>
    </div>
</div>
<div class="well">
    <br /><hr />
    <table class="table table-bordered">
            <tr class="titulo2">
                <th colspan="3" style="text-align: center" >Bairro</th>
            </tr>
            <tr>
                    <td><div class="pull-right"><strong>Município:</strong></div></td>
                    <td><?php echo $view_sql["id_municipio"]; ?></td>
            </tr>
            <tr>
                    <td width='50%'><div class="pull-right"><strong>Bairro:</strong></div></td>
                    <td><?php echo $view_sql["nome"]; ?></td>
            </tr>
            
            
    </table>
</div>