<form method="post" action="/sistema/setor/inserir/" class="form-horizontal">
<div class="well">
    <div class="navbar">
        <div class="span4"><h4>Setor - <a href="/sistema/setor/inserir/">Cadastro</a></h4></div>
        <div class="navbar-inner pull-right">
           
            <button type="submit" class="btn btn-primary">Salvar <i class="fa fa-save"></i></button>
            <button type="reset" class="btn btn-danger">Limpar <i class="fa fa-trash-o"></i></button>
            <a class="btn" href="/sistema/setor/index/" title="Voltar"> Voltar <i class="fa fa-reply"></i></a>
         
        </div>
    </div>
    <br /><hr />
        <div class="control-group">
            <label for="descricao" class="control-label">Descrição:</label>
            <div class="controls">
                <input type="text" name="descricao" id="descricao" value="" class="span5" />
            </div>
        </div>
        <div class="control-group">
            <label for="chave" class="control-label">Sigla:</label>
            <div class="controls">
                <input type="text" name="chave" id="chave" value="" class="span2" />
            </div>
        </div>
        
</div>
</form>