<?php
$resp = new ResponsavelModel($_SESSION['responsavel']);
$pes = new PessoaModel($resp->id_pessoa);
?>
<div class="row">
    <section class="col-md-12">
        <div class="box box-info">
            <div class="box-header ui-sortable-handle" >
              <i class="fa fa-legal"></i>
              <h3 class="box-title">Alunos - <strong>Responsável:</strong> <?php echo UtilHelper::primeiraMaiuscula($pes->nome);?></h3>
              <!-- tools box -->
              <div class="pull-right box-tools">
                    <a class="btn btn-default pesquisar" href="#" title="Pesquisar" data-toggle="tooltip"><i class="fa fa-search"></i></a>
                    <a class="btn btn-default" href="/sistema/responsavel/alunoinserir/" data-toggle="tooltip" title="Adicionar"><i class="fa fa-plus-circle"></i></a>
                    <a class="btn btn-default" href="/sistema/responsavel/index/" data-toggle="tooltip" title="Voltar"> <i class="fa fa-reply"></i></a>
              </div>
            </div>
            <div class="box-body">
    <div class="col-md-4 well-sm areapesquisa">
    <form class="form-horizontal" action="/sistema/responsavel/index/" method="post">
        <div class="input-group input-group-sm">
            <input type="text" class="form-control" name="nome"placeholder="Buscar Nome...">
            <span class="input-group-btn">
              <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i> Buscar</button>
              <a class="btn btn-danger" href="/sistema/responsavel/index/" title=""><i class="fa fa-close"></i> Limpar Busca</a>
            </span>
        </div>
    </form>
    </div>
            <table class="table table-bordered">
                <tbody>
                    <tr class="itemTitulo2">
                        <th>ID</th>
                        <th>Nome</th>
                        <th><center>Operações</center></th>
                    </tr>
                    <?php foreach ($view_sql as $sql){
                        $pes = new PessoaModel($sql['id_pessoa']);
                    ?>
                    <tr>
                        <td><?php echo $sql['id_aluno']?></td>
                        <td><?php echo $pes->nome;?></td>
                        <td>
                            <center>
                            <div class="btn-group mod">
                                <a class="btn btn-small btn-success" href="<?php echo "/sistema/responsavel/alunovisualizar/id/{$sql["id_aluno"]}";?>" title="Visualizar"><i class="fa fa-search"></i></a>
                                <a class="btn btn-small btn-warning" href="<?php echo "/sistema/responsavel/alunoeditar/id/{$sql["id_aluno"]}";?>" title="Editar"><i class="fa fa-edit"></i></a>
                                <a href="#id<?php echo "{$sql["id_aluno"]}";?>" role="button" class="btn btn-danger" data-toggle="modal"><i class="fa fa-trash-o"></i></a>
                            </div>
                            </center>
                        </td>
                    </tr>
                    <?php } ?>
                </tbody>
            </table>
            </div>
        </div>
        </section>
</div>
<?php foreach ($view_sql as $sql){ ?>
<div class="modal fade" id="id<?php echo "{$sql["id_aluno"]}";?>" tabindex="-1" role="dialog" aria-labelledby="id<?php echo "{$sql["id_aluno"]}";?>">
  <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          <h3 id="myModalLabel">Deseja Realmente Apagar este responsavel?</h3>
        </div>
        <div class="modal-body">
            <p>O registro será apagado permanente!</p>
        </div>
        <div class="modal-footer">
            <a class="btn btn-danger" href="<?php echo "/sistema/responsavel/alunoexcluir/id/{$sql["id_aluno"]}";?>" title="Excluir">Sim</a>
            <button class="btn btn-info" data-dismiss="modal" aria-hidden="true">Cancelar</button>
        </div>
    </div>
  </div>
</div>
<?php } ?>
