<form method="post" action="/sistema/responsavel/inserir" class="form-horizontal" name="form1"  enctype="multipart/form-data" id="form1" runat="server">
<div class="row">
    <section class="col-md-12">
    <div class="nav-tabs-custom">
        <!-- Tabs within a box -->
        <ul class="nav nav-tabs ui-sortable-handle">
          <li id="ab1" class="active"><a href="#aba1" data-toggle="tab">Inserir Responsável</a></li>
          <a style="margin: 5px" class="btn btn-default pull-right" href="/sistema/responsavel/index/"data-toggle="tooltip" title="Voltar"><i class="fa fa-reply"></i></a>
          <button style="margin: 5px" type="submit" class="btn btn-primary pull-right" data-toggle="tooltip" title="Salvar"><i class="fa fa-save"></i></button>
          
        </ul>
    </div>
    <div class="tab-content no-padding">
        <div class="tab-pane active" id="aba1">
        <div class="box box-info">
            <div class="box-header with-border">
              <h3 class="box-title">Inserir</h3>
            </div>
            <div class="box-body">
                <div class="row">
                    <div class="col-xs-4">
                        <label for="">Nome Completo:</label>
                        <input type="text" name="nome" class="form-control" placeholder="Nome completo">
                    </div>
                    <div class="col-xs-4">
                        <label for="">CPF:</label>
                        <input type="text" name="cpf"  class="form-control cpf" placeholder="___.___.___-__">
                    </div>
                    <div class="col-xs-4">
                        <label for="">Email:</label>
                        <input type="text" name="email" class="form-control" placeholder="email@email.com">
                    </div>
                </div>
            </div>
        </div>
        </div>   
    </div>
    </section>
</div>
</form>