<div class="row">
    <section class="col-md-12">
    <div class="box box-info">
        <div class="box-header ui-sortable-handle" >
          <i class="fa fa-legal"></i>
          <h3 class="box-title">Status de Matricula</h3>
          <!-- tools box -->
          <div class="pull-right box-tools">
                <a class="btn btn-default" data-toggle="tooltip" href="/sistema/matriculastatus/index/" title="Voltar"><i class="fa fa-reply"></i></a>
          </div><!-- /. tools -->
        </div>
        <div class="box-body">
            <div class="row">
                <div class="col-md-6">
                    <div class="well">
                        <dl class="dl-horizontal">
                            <dt>Status:</dt>
                            <dd><?php echo $view_sql['descricao'];?></dd>
                            <dt>Chave:</dt>
                            <dd><?php echo $view_sql['chave'];?></dd>
                        </dl>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </section>
</div>