<div class="well">
<div class="navbar">
    <div class="span4"><h4>Modulo - <a href="/sistema/modulo/">Listar Controller</a></h4></div>
    <div class="navbar-inner pull-right">
        <div class="">
        <a class="btn" href="/sistema/modulo/inserir_controller/" title="Adicionar">Adicionar Controller <i class="fa fa-plus-circle"></i></a>
        <a class="btn" href="/sistema/index/index/" title="Voltar"> Voltar <i class="fa fa-reply"></i></a>
    </div>
    </div>
</div>
    <br />
    <hr />
    <table class="table table-bordered">
        <tr>
            <th colspan="7" class="titulo2">Controller</th>
        </tr>
        <tbody>
            <tr class="itemTitulo2">
                <th>Id</th>
                <th>Controller</th>
            </tr>
            <?php foreach ($view_sql as $sql){?>
            <tr class="item2">
                <td><?php echo $sql['id_controller'];?></td>
                <td><?php echo $sql['controller'];?></td>
                <td>
                    <div class="btn-group">
                        <a class="btn btn-success" href="<?php echo "/sistema/modulo/visualizar_controller/id/{$sql["id_controller"]}";?>" title="Visualizar"><i class="fa fa-search"></i></a>
                        <a class="btn btn-warning" href="<?php echo "/sistema/modulo/editar_controller/id/{$sql["id_controller"]}";?>" title="Editar"><i class="fa fa-edit"></i></a>
                        <a class="btn btn-danger" href="<?php echo "/sistema/modulo/excluir_controller/id/{$sql["id_controller"]}";?>" title="Excluir" onclick="exclui(event);"><i class="fa fa-trash"></i></a>
                    </div>
                </td>
            </tr>
            <?php } ?>
    </tbody>
</table>
</div>