<div class="well">
<div class="navbar">
    <div class="span4"><h4>Modulo - <a href="/sistema/modulo/">Listar</a></h4></div>
    <div class="navbar-inner pull-right">
        <div class="">
        <a class="btn" href="/sistema/modulo/inserir/" title="Adicionar">Adicionar Action <i class="fa fa-plus-circle"></i></a>
        <a class="btn" href="/sistema/index/index/" title="Voltar"> Voltar <i class="fa fa-reply"></i></a>
    </div>
    </div>
</div>
    <br />
    <hr />
    <table class="table table-bordered">
        <tr>
            <th colspan="7" class="titulo2">Actions</th>
        </tr>
        <tbody>
            <tr class="itemTitulo2">
                <td>Controller</td>
                <td>Action</td>
                <td>Principal</td>
                <td>Operações</td>
            </tr>
            <?php 
                foreach ($view_sql as $sql){
                    $controller = new ControllerModel($sql['id_controller']);
            ?>
            <tr class="item2">
                <td><?php echo $controller->controller; ?></td>
                <td><?php echo $sql['action']; ?></td>
                <td><?php echo $sql['principal']; ?></td>
                <td>
                    <div class="btn-group">
                        <a class="btn btn-success" href="<?php echo "/sistema/modulo/visualizar/id/{$sql["id_action"]}";?>" title="Visualizar"><i class="fa fa-search"></i></a>
                        <a class="btn btn-warning" href="<?php echo "/sistema/modulo/editar/id/{$sql["id_action"]}";?>" title="Editar"><i class="fa fa-edit"></i></a>
                        <a class="btn btn-danger" href="<?php echo "/sistema/modulo/excluir/id/{$sql["id_action"]}";?>" title="Excluir" onclick="exclui(event);"><i class="fa fa-trash"></i></a>
                    </div>
                </td>
            </tr>
            <?php } ?>
    </tbody>
</table>
</div>