<form method="post" action="/sistema/modulo/inserir_controller/" class="form-horizontal">
<div class="well">
    <div class="navbar">
        <div class="span4"><h4>Modulo - <a href="/sistema/modulo/inserir_controller/">Inserir Controller</a></h4></div>
        <div class="navbar-inner pull-right span4">
            <div class="">
            <button type="submit" class="btn btn-primary">Salvar <i class="fa fa-save"></i></button>
            <button type="reset" class="btn btn-danger">Limpar <i class="fa fa-trash-o"></i></button>
            <a class="btn" href="/sistema/modulo/index/" title="Voltar"> Voltar <i class="fa fa-reply"></i></a>
            </div>
        </div>
    </div>
    <br /><hr />
    <div class="control-group">
        <label for="controller" class="control-label">Controller:</label>
        <div class="controls">
            <input type="text" name="controller" id="nome" size="5" value="" class="span2" />
        </div>
    </div>
</div>
</form>