<div class="well">
<div class="navbar">
    <div class="span4"><h4>Action - <a href="/sistema/modulo/visualizar/id/<?php echo $view_sql["id_action"]; ?>">Visualizar</a></h4></div>
    <div class="navbar-inner pull-right span4">
        <div class="">
            <a class="btn" href="/sistema/modulo/index/" title="Voltar"> Voltar <i class="fa fa-reply"></i></a>
        </div>
    </div>
</div>
    <br /> <hr />
    <table class="table table-bordered">
            <tr class="titulo2">
                <th colspan="3" style="text-align: center" >Action</th>
            </tr>
            <tr>
                <td width="20%"><div class="pull-right"><strong>Id:</strong></div></td>
                <td><?php echo $view_sql["id_action"]; ?></td>
            </tr>
            <tr>
                <td width="20%"><div class="pull-right"><strong>Action:</strong></div></td>
                <td><?php echo $view_sql["action"]; ?></td>
            </tr>
            <tr>
                <td><div class="pull-right"><strong>Principal:</strong></div></td>
                <td><?php echo $view_sql["principal"]; ?></td>
            </tr>
    </table>
</div>