<form method="post" action="/sistema/anoletivo/inserir/" class="form-horizontal" name="form1"  enctype="multipart/form-data" id="form1" runat="server">
<div class="row">
    <section class="col-md-12">
    <div class="nav-tabs-custom">
        <!-- Tabs within a box -->
        <ul class="nav nav-tabs ui-sortable-handle">
          <li class="active"><a href="#prot" data-toggle="tab">Cadastro de Ano Segmento</a></li>
          <a style="margin: 5px" class="btn btn-default pull-right" href="/sistema/anoletivo/index/"data-toggle="tooltip" title="Voltar"><i class="fa fa-reply"></i></a>
          <button style="margin: 5px" type="submit" class="btn btn-primary pull-right" data-toggle="tooltip" title="Salvar"><i class="fa fa-save"></i></button>
          <button style="margin: 5px" type="reset" class="btn btn-danger pull-right" data-toggle="tooltip" title="Limpar"><i class="fa fa-trash-o"></i></button>
        </ul>
    </div>
        <div class="tab-content no-padding">
            <div class="tab-pane active" id="prot">
                <div class="box box-info">
                    <div class="box-header ui-sortable-handle" >
                      <i class="fa fa-envelope"></i>
                      <h3 class="box-title">Ano Segmento</h3>
                      <!-- tools box -->
                      <div class="pull-right box-tools">
                        
                      </div><!-- /. tools -->
                    </div>
                    <div class="box-body">
                        <div class="row">
                            <div class="col-md-3 col-md-offset-1">
                                <div class="form-group">
                                    <label>Ano</label>
                                    <select class="form-control" name="id_ano">
                                        <option> Selecione </option>
                                        <?php foreach ($view_ano as $ano){ ?>
                                        <option value="<?php echo $ano['id_ano'];?>"> <?php echo $ano['descricao'];?> </option>
                                        <?php } ?>
                                    </select>
                                </div>
                                <div class="form-group" >
                                    <label> Segmento </label>
                                    <select class="form-control" name="id_segmento">
                                        <option> Selecione </option>
                                        <?php foreach ($view_seg as $seg){ ?>
                                        <option value="<?php echo $seg['id_segmento'];?>"> <?php echo $seg['descricao'];?> </option>
                                        <?php } ?>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
</form>
