<div class="row">
    <div class="col-lg-3 col-xs-6">
          <!-- small box -->
        <div class="small-box bg-red">
          <div class="inner">
            <h3>Inadimplêntes<sup style="font-size: 20px"></sup></h3>

            <p>Protesto</p>
          </div>
          <div class="icon">
            <i class="fa fa-bar-chart-o"></i>
          </div>
          <a href="/sistema/relatorio/protestoinadimplencia" class="small-box-footer">
            Gerar Relatório <i class="fa fa-arrow-circle-right"></i>
          </a>
        </div>
    </div>
    <div class="col-lg-3 col-xs-6">
          <!-- small box -->
        <div class="small-box bg-green">
          <div class="inner">
            <h3>Adimplentes<sup style="font-size: 20px"></sup></h3>

            <p>Protesto</p>
          </div>
          <div class="icon">
            <i class="fa fa-bar-chart-o"></i>
          </div>
          <a href="/sistema/relatorio/protestoadimplente" class="small-box-footer">
            Gerar Relatório <i class="fa fa-arrow-circle-right"></i>
          </a>
        </div>
    </div>
</div>