<div class="well">
<div class="navbar">
    <div class="span4"><h4>Função - <a href="/sistema/funcao/">Listar</a></h4></div>
    <div class="navbar-inner pull-right">
        <div class="">
        <a class="btn" href="/sistema/funcao/inserir/" title="Adicionar">Adicionar Função <i class="icon-plus-sign"></i></a>
        <a class="btn" href="/sistema/index/index/" title="Voltar"> Voltar <i class="icon-circle-arrow-left"></i></a>
    </div>
    </div>
</div>
    <br />
    <hr />
    <table class="table table-bordered">
        <tr>
            <th colspan="7" class="titulo2">Funções</th>
        </tr>
        <tbody>
            <tr class="itemTitulo2">
                <td>ID</td>
                <td>Descrição</td>
                <td>Salário</td>
                <td>Carga Horária</td>
                <td>Operações</td>
            </tr>
            <?php foreach ($view_sql as $sql){?>
            <tr class="item2">
                <td><div class="badge badge-inverse"><?php echo $sql['id_funcao'];?></div></td>
                <td><?php echo $sql['salario'];?></td>
                <td><?php echo $sql['descricao'];?></td>
                <td><?php echo $sql['carga_horaria'];?></td>
                <td>
                    <div class="btn-group">
                        <a class="btn btn-success" href="<?php echo "/sistema/funcao/visualizar/id/{$sql["id_funcao"]}";?>" title="Visualizar"><i class="icon-zoom-in icon-white"></i></a>
                        <a class="btn btn-warning" href="<?php echo "/sistema/funcao/editar/id/{$sql["id_funcao"]}";?>" title="Editar"><i class="icon-edit icon-white"></i></a>
                        <a class="btn btn-danger" href="<?php echo "/sistema/funcao/excluir/id/{$sql["id_funcao"]}";?>" title="Excluir" onclick="exclui(event);"><i class="icon-trash icon-white"></i></a>
                    </div>
                </td>
            </tr>
            <?php } ?>
    </tbody>
</table>
</div>