<div class="navbar span6">
    <div class="navbar-inner">
        <div class="">
            <a class="btn" href="/sistema/funcao/index/inserir" title="Adicionar">Adicionar <i class="icon-plus-sign"></i></a>
            <a class="btn" href="/sistema/funcao/editar/id/<?php echo $view_sql["id_funcao"]; ?>" title="Editar"> <i class="icon-edit"></i> Editar</a>
            <a class="btn" href="/sistema/funcao/excluir/id/<?php echo $view_sql["id_funcao"]; ?>" title="Excluir"><i class="icon-trash"></i> Excluir</a>
            <a class="btn" href="/sistema/funcao/index/" title="Voltar"> Voltar <i class="icon-circle-arrow-left"></i></a>
        </div>
    </div>
</div>
<div class="span11">
    <table class="table table-bordered">
            <tr class="titulo2">
                <th colspan="3" style="text-align: center" >Dados da Função</th>
            </tr>
            <tr>
                    <td width='50%'><div class="pull-right"><strong>Função:</strong></div></td>
                    <td><?php echo $view_sql["descricao"]; ?></td>
            </tr>
            <tr>
                    <td><div class="pull-right"><strong>Salario:</strong></div></td>
                    <td><?php echo $view_sql["salario"]; ?></td>
            </tr>
            <tr>
                    <td><div class="pull-right"><strong>Carga Horária:</strong></div></td>
                    <td><?php echo $view_sql["carga_horaria"]; ?></td>
            </tr>
    </table>
</div>