<div class="row">
    <div class="col-lg-3 col-xs-6">
          <!-- small box -->
        <div class="small-box bg-green">
          <div class="inner">
            <h3><sup style="font-size: 20px">Relação de Alunos</sup></h3>

            <p>Acadêmico</p>
          </div>
          <div class="icon">
            <i class="fa fa-graduation-cap"></i>
          </div>
          <a href="/sistema/relatorioacademico/alunos" class="small-box-footer">
            Gerar Relatório <i class="fa fa-arrow-circle-right"></i>
          </a>
        </div>
    </div>
    <div class="col-lg-3 col-xs-6">
          <!-- small box -->
        <div class="small-box bg-blue">
          <div class="inner">
            <h3><sup style="font-size: 20px">Matriculados / Rematriculados</sup></h3>

            <p>Acadêmico</p>
          </div>
          <div class="icon">
            <i class="fa fa-bar-chart-o"></i>
          </div>
          <a href="/sistema/relatorioacademico/matriculados" class="small-box-footer">
            Gerar Relatório <i class="fa fa-arrow-circle-right"></i>
          </a>
        </div>
    </div>
    <div class="col-lg-3 col-xs-6">
          <!-- small box -->
        <div class="small-box bg-yellow">
          <div class="inner">
            <h3><sup style="font-size: 20px">Lista de Espera</sup></h3>

            <p>Acadêmico</p>
          </div>
          <div class="icon">
            <i class="fa fa-calendar"></i>
          </div>
          <a href="/sistema/relatorioacademico/espera" class="small-box-footer">
            Gerar Relatório <i class="fa fa-arrow-circle-right"></i>
          </a>
        </div>
    </div>
    
</div>