<div class="row">
    <div class="col-md-8">
        <div class="box box-info">
            <div class="box-header with-border">
                <i class=" fa fa-file-text-o"></i>
              <h3 class="box-title">Buscar por:</h3>
            </div>
            <form method="post" action="" target="_blank">
            <div class="box-body">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <div class="form-group">
                                <label>Turma</label>
                                <select class="form-control" name="id_turma">
                                    <option value="">Selecione</option>
                                    <?php foreach ($view_turma as $turma){ ?>
                                    <option value='<?php echo $turma['id_turma'] ?>'><?php echo $turma['descricao'] ?></option>
                                    <?php } ?>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <div class="form-group">
                                <label>Tipo</label>
                                <select class="form-control" name="id_matricula_status">
                                    <option value="">Selecione</option>
                                    <?php foreach ($view_status as $stt){
                                        if($stt['id_matricula_status'] != 3){
                                    ?>
                                    <option value='<?php echo $stt['id_matricula_status'] ?>'><?php echo $stt['descricao'] ?></option>
                                    <?php }} ?>
                                </select>
                            </div>
                        </div>
                    </div>
                    
                </div>
                <div class="text-red">
                        <strong>Obs:</strong> Esse relatório é definido por ordem de alfabetica.
                </div>
                <div class="box-footer">
                    <button type="submit" class="btn btn-primary pull-right"><i class="fa fa-print"></i> Gerar</button>
                </div>
        </form>
        </div>
    </div>
</div>
</div>