<?php
    if($login){
        $pes = new PessoaModel($_SESSION["userData"]["id_pessoa"]);
        $fotoperfil = "/sistema/public/img/user-default.png";
        if($pes->foto){
            $fotoperfil = $pes->foto;
        }
?>
<header class="main-header">
        <!-- Logo -->
        <a href="#" class="logo">
          <!-- mini logo for sidebar mini 50x50 pixels -->
          <span class="logo-mini"><b>S</b>ch</span>
          <!-- logo for regular state and mobile devices -->
          <span class="logo-lg"><b>School</b>1.0</span>
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top" role="navigation">
          <!-- Sidebar toggle button-->
           <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
            
          <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
              <li class="dropdown user user-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <img src="<?php echo $fotoperfil; ?>" class="user-image" alt="User Image"/>
                  <span class="hidden-xs"><?php echo $pes->nome; ?></span>
                </a>
                <ul class="dropdown-menu">
                  <!-- User image -->
                  <li class="user-header">
                    <img src="<?php echo $fotoperfil; ?>" class="img-circle" alt="User Image" />
                    <p>
                      <?php echo UtilHelper::formataNome($pes->nome);?> - Administrador
                      <small>Ultimo Acesso 28 Abril 2015</small>
                    </p>
                  </li>
                  <!-- Menu Body -->
                  <li class="user-body">
                    <div class="col-xs-4 text-center">
                      <a href="#">Coordenador</a>
                    </div>
                    <div class="col-xs-4 text-center">
                      <a href="#">Professor</a>
                    </div>
                    <div class="col-xs-4 text-center">
                      <a href="#">Aluno</a>
                    </div>
                  </li>
                  <!-- Menu Footer-->
                  <li class="user-footer">
                    <div class="pull-left">
                      <a href="#" class="btn btn-success btn-flat"><i class="fa fa-edit"></i> Perfil</a>
                    </div>
                    <div class="pull-right">
                        <a href="/sistema/auth/logout/" class="btn btn-danger btn-flat"><i class="fa fa-power-off"></i> Sair</a>
                    </div>
                  </li>
                </ul>
              </li>
              <!--
              <li>
                <a href="#" data-toggle="control-sidebar"><i class="fa fa-comments-o"></i></a>
              </li>
              -->
            </ul>
          </div>
        </nav>
      </header>
 <?php } ?>