<form method="post" action="/sistema/orientador/inserir/" class="form-horizontal" enctype="multipart/form-data" id="form1" runat="server">
<div class="row">
    <div class="span5">            
        <ul class="breadcrumb">
            <li><a href="/sistema/index/index/"><i class="fa fa-home"></i> Início</a> <span class="divider">/</span></li>
            <li><a href="/sistema/orientador/index/"><i class="fa fa-user"></i> Colaborador Efetivo</a> <span class="divider">/</span></li>
            <li class="active">Cadastro</li>
        </ul>
    </div>
    <div class="pull-right">
        <a class="btn" href="/sistema/orientador/index/" title="Voltar"> Voltar <i class="fa fa-reply"></i></a>
    </div>
</div>
<div class="well">
    <legend>Dados do Pessoais <div class="span4 pull-right" style="font-size: 14px;">Campos com "<span class="text-error"><i class="fa fa-asterisk"></i></span>" Obrigatorios!</div></legend>
    <div class="control-group" id="mat">
        <label for="matricula" class="control-label">Matricula:</label>
        <div class="controls">
            <input type="text" name="matricula" id="matricula" value="" class="span2" required=""> <span class="text-error">*</span>
        </div>
    </div>
    <div class="control-group">
        <label for="foto" class="control-label">Foto:</label>
        <div class="controls">
            <img id="blah" class="img-circle" src="/sistema/public/img/user-default.png" alt="" style="width: 100px" />
            <input type='file' id="imgInp" name="foto"/>

        </div>
    </div>
    <div class="control-group">
        <label for="nome" class="control-label">Nome Completo:</label>
        <div class="controls">
            <input type="text" name="nome" id="nome" value="" class="span5" required=""/> <span class="text-error">*</span>
        </div>
    </div>
    <div class="control-group">
        <label for="cpf" class="control-label">cpf:</label>
        <div class="controls">
            <input type="text" name="cpf" class="span2 cpf" maxlength="14" placeholder="___.___.___-___" required=""> <span class="text-error">*</span>
        </div>
    </div>
    <div class="control-group">
        <label for="rg" class="control-label">Rg:</label>
        <div class="controls">
            <input type="text" name="rg" id="rg" value="" class="span2" required=""/> 
            UF:
            <select name="id_estado" class="span2">
                <option value="">=> Selecione <=</option>
                <?php foreach ($view_est as $est){ ?>
                    <option value="<?php echo $est["id_estado"]; ?>"><?php echo $est["sigla"]; ?></option>
                <?php } ?>
            </select> <span class="text-error">*</span>
        </div> 
    </div>
    <div class="control-group">
        <label for="email" class="control-label">Email:</label>
        <div class="controls">
            <input type="email" name="email" id="chave" value="" class="span5" required=""/> <span class="text-error">*</span>
        </div>
    </div>
    <div class="control-group">
        <label for="telefone" class="control-label">Telefone:</label>
        <div class="controls">
            <input type="text" name="telefone" id="telefone" value="" class="span2 telefone" maxlength="14" placeholder="(__) ___-____"/>
        </div>
    </div>
     <div class="control-group">
        <label for="principal" class="control-label">Sexo:</label>
        <div class="controls">
            <label class="radio">
            <input type="radio" name="sexo" id="principal" size="5" value="M" />
            Masculino.
            </label>
            <label class="radio">
            <input type="radio" name="sexo" id="principal" size="5" value="F" />
            Feminino.
            </label>
        </div> <span class="text-error">*</span>
    </div>
    <div class="control-group">
        <label for="data_nascimento" class="control-label">Data de Nascimento:</label>
        <div class="controls">
            <div class="input-append">
                <input type="text" name="data_nascimento" id="data_nascimento" value="" class="span2 data calendario" required="" <span class="text-error">*</span>
                <span class="add-on"><i class="fa fa-calendar"></i></span>
            </div>
            
        </div>
    </div>
</div>
    <div class="well">
    <legend>Endereco <div class="span4 pull-right" style="font-size: 14px;">Campos com "<span class="text-error"><i class="fa fa-asterisk"></i></span>" Obrigatorios!</div></legend>
    <div class="control-group">
        <label for="endereco" class="control-label">Endereço:</label>
        <div class="controls">
            <input type="text" name="endereco" id="endereco" value="" class="span5" /> <span class="text-error">*</span>
            Nº:
            <input type="text" name="numero" id="numero" value="" class="span1" /> <span class="text-error">*</span>
        </div>
    </div>
    <div class="control-group">
        <label for="municipio" class="control-label">Municipio:</label>
        <div class="controls">
            <select name="id_municipio" class="span2" id="municipio" required="">
                    <option value="">=> Selecione <=</option>
                <?php foreach ($view_mun as $mun){ ?>
                    <option value="<?php echo $mun["id_municipio"]; ?>"><?php echo $mun["nome"]; ?></option>
                <?php } ?>
            </select> <span class="text-error">*</span>
            Bairro:

            <select name="id_bairro" class="span2" id="load_bairro">
                <option value="">Selecione o Bairro</option>
            </select>

        </div>
    </div>
    <div class="control-group">
        <label for="cep" class="control-label">CEP:</label>
        <div class="controls">
            <input type="text" name="cep" id="cep" value="" class="span2 cep" maxlength="10" placeholder="_____-___" required=""/> <span class="text-error">*</span>
        </div>
    </div>
    <div class="control-group">
        <label for="complemento" class="control-label">Complemento:</label>
        <div class="controls">
            <input type="text" name="complemento" id="complemento" value="" class="span5" placeholder="Ex.: Bloco A." />
        </div>
    </div>
    <div class="control-group">
        <label for="" class="control-label"></label>
        <div class="controls">
            <button type="submit" class="btn btn-primary">Salvar <i class="fa fa-save"></i></button>
        <button type="reset" class="btn btn-danger">Limpar <i class="fa fa-trash-o"></i></button>
        </div>
    </div>
    </div>
    
    
        
</form>