<form method="post" action="/sistema/taxas/editar/id/<?php echo $view_sql['id_taxas'];?>/" class="form-horizontal" name="form1"  enctype="multipart/form-data" id="form1" runat="server">
<div class="row">
    <section class="col-md-12">
    <div class="nav-tabs-custom">
        <!-- Tabs within a box -->
        <ul class="nav nav-tabs ui-sortable-handle">
          <li id="ab1" class="active"><a href="#aba1" data-toggle="tab">Editar taxas</a></li>
          <a style="margin: 5px" class="btn btn-default pull-right" href="/sistema/taxas/index/"data-toggle="tooltip" title="Voltar"><i class="fa fa-reply"></i></a>
          <button style="margin: 5px" type="submit" class="btn btn-primary pull-right" data-toggle="tooltip" title="Salvar"><i class="fa fa-save"></i></button>
          
        </ul>
    </div>
    <div class="tab-content no-padding">
        <div class="tab-pane active" id="aba1">
        <div class="box box-info">
                    <div class="box-header ui-sortable-handle" >
                      <i class="fa fa-envelope"></i>
                      <h3 class="box-title">Taxas</h3>
                      <!-- tools box -->
                      <div class="pull-right box-tools">
                        
                      </div><!-- /. tools -->
                    </div>
                    <div class="box-body">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="descricao" class="col-sm-3 control-label">Nome da Taxa:</label>
                                    <div class="col-sm-6">
                                        <input type="text" value="<?php echo $view_sql['descricao'];?>" class="form-control" name="descricao" placeholder="">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
        </div>   
            
        <div class="tab-pane" id="aba2">
            <div class="row">
                <div class="col-md-6">
                <div class="box box-primary">
                <div class="box-header ui-sortable-handle" style="cursor: move;">
                  <i class="ion ion-clipboard"></i>
                  <h3 class="box-title">Taxas</h3>
                  <div class="pull-right box-tools">
                  <a href="#" class="btn btn-sm  btn-default pull-right" data-toggle="modal" data-target="#myModal"><i class="fa fa-plus"></i> Add Taxas</a>
                  </div>
                </div><!-- /.box-header -->
                <div class="box-body">
                <ul class="todo-list ui-sortable">
                    <li>
                      <span class="handle ui-sortable-handle">
                        <i class="fa fa-ellipsis-v"></i>
                        <i class="fa fa-ellipsis-v"></i>
                      </span>
                      <input type="checkbox" value="" name="">
                      <span class="text">taxa 1</span>
                      <small class="label label-info"><i class="fa fa-clock-o"></i> 4423 </small>
                      <div class="tools">
                        <i class="fa fa-edit"></i>
                        <i class="fa fa-trash-o"></i>
                      </div>
                    </li>
                    <li class="">
                      <!-- drag handle -->
                      <span class="handle ui-sortable-handle">
                        <i class="fa fa-ellipsis-v"></i>
                        <i class="fa fa-ellipsis-v"></i>
                      </span>
                      <!-- checkbox -->
                      <input type="checkbox" value="" name="">
                      <!-- todo text -->
                      <span class="text">taxa 2</span>
                      <!-- Emphasis label -->
                      <small class="label label-danger"><i class="fa fa-clock-o"></i> 245 </small>
                      <!-- General tools such as edit or delete-->
                      <div class="tools">
                        <i class="fa fa-edit"></i>
                        <i class="fa fa-trash-o"></i>
                      </div>
                    </li>
                    <li>
                      <span class="handle ui-sortable-handle">
                        <i class="fa fa-ellipsis-v"></i>
                        <i class="fa fa-ellipsis-v"></i>
                      </span>
                      <input type="checkbox" value="" name="">
                      <span class="text">taxa 3</span>
                      <small class="label label-warning"><i class="fa fa-clock-o"></i> 14532 </small>
                      <div class="tools">
                        <i class="fa fa-edit"></i>
                        <i class="fa fa-trash-o"></i>
                      </div>
                    </li>
                </ul>
                </div><!-- /.box-body -->
                </div>
                </div>
                <div class="col-md-6">
                    <div class="box box-primary">
                    <div class="box-header ui-sortable-handle" style="cursor: move;">
                      <i class="ion ion-clipboard"></i>
                      <h3 class="box-title">Anexos</h3>
                      <div class="pull-right box-tools">
                      <a href="#" class="btn btn-sm  btn-default pull-right" ><i class="fa fa-upload"></i> Upload</a>
                      </div>
                    </div><!-- /.box-header -->
                <div class="box-body">
                <ul class="todo-list ui-sortable">
                    <li>
                      <span class="handle ui-sortable-handle">
                        <i class="fa fa-ellipsis-v"></i>
                        <i class="fa fa-ellipsis-v"></i>
                      </span>
                      <input type="checkbox" value="" name="">
                      <span class="text">taxa 1</span>
                      <small class="label label-info"><i class="fa fa-clock-o"></i> 4423 </small>
                      <div class="tools">
                        <i class="fa fa-edit"></i>
                        <i class="fa fa-trash-o"></i>
                      </div>
                    </li>
                    <li class="">
                      <!-- drag handle -->
                      <span class="handle ui-sortable-handle">
                        <i class="fa fa-ellipsis-v"></i>
                        <i class="fa fa-ellipsis-v"></i>
                      </span>
                      <!-- checkbox -->
                      <input type="checkbox" value="" name="">
                      <!-- todo text -->
                      <span class="text">taxa 2</span>
                      <!-- Emphasis label -->
                      <small class="label label-danger"><i class="fa fa-clock-o"></i> 245 </small>
                      <!-- General tools such as edit or delete-->
                      <div class="tools">
                        <i class="fa fa-edit"></i>
                        <i class="fa fa-trash-o"></i>
                      </div>
                    </li>
                    <li>
                      <span class="handle ui-sortable-handle">
                        <i class="fa fa-ellipsis-v"></i>
                        <i class="fa fa-ellipsis-v"></i>
                      </span>
                      <input type="checkbox" value="" name="">
                      <span class="text">taxa 3</span>
                      <small class="label label-warning"><i class="fa fa-clock-o"></i> 14532 </small>
                      <div class="tools">
                        <i class="fa fa-edit"></i>
                        <i class="fa fa-trash-o"></i>
                      </div>
                    </li>
                </ul>
                </div><!-- /.box-body -->
                </div>
                </div>
            </div>
        </div>
    </div>
    </section>
</div>
</form>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Lista de Taxas</h4>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="fa fa-close"></i></button>
        <button type="button" class="btn btn-primary"><i class="fa fa-save"></i></button>
      </div>
    </div>
  </div>
</div>