<form method="post" action="/sistema/protesto/editar/id/<?php echo $view_sql['id_protesto'];?>/" class="form-horizontal" name="form1"  enctype="multipart/form-data" id="form1" runat="server">
<div class="row">
    <section class="col-md-12">
    <div class="nav-tabs-custom">
        <!-- Tabs within a box -->
        <ul class="nav nav-tabs ui-sortable-handle">
          <li id="ab1" class="active"><a href="#aba1" data-toggle="tab">Editar Protesto</a></li>
          <a style="margin: 5px" class="btn btn-default pull-right" href="/sistema/protesto/index/"data-toggle="tooltip" title="Voltar"><i class="fa fa-reply"></i></a>
          <button style="margin: 5px" type="submit" class="btn btn-primary pull-right" data-toggle="tooltip" title="Salvar"><i class="fa fa-save"></i></button>
          
        </ul>
    </div>
    <div class="tab-content no-padding">
        <div class="tab-pane active" id="aba1">
        <div class="box box-info">
            <div class="box-header ui-sortable-handle" >
              <i class="fa fa-envelope"></i>
              <h3 class="box-title">Dados do protesto</h3>
              <!-- tools box -->
              <div class="pull-right box-tools">
                
              </div><!-- /. tools -->
            </div>
            <div class="box-body">
                <div class="row">
                    <div class="col-md-6">
                    <input type="hidden" name="id_protesto" value="<?php echo $view_sql['id_protesto'];?>"/>
                    <div class="form-group">
                        <input type="hidden" name="id_responsavel" value="<?php echo $view_sql["id_responsavel"];?>" />
                        <label for="responsavel" class="col-sm-2 control-label">Responsável:</label>
                        <div class="col-sm-6">
                            <select class=" form-control" id="responsavel" disabled="">
                                <option value="">=> Selecione <=</option>
                                <?php foreach ($view_resp as $resp){ 
                                    $pes =  new PessoaModel($resp['id_pessoa']);
                                ?>
                                <option value="<?php echo $resp["id_responsavel"]; ?>"<?php ($view_sql["id_responsavel"] == $resp["id_responsavel"]) ? print " selected" : print ""; ?>><?php echo $pes->nome; ?></option>
                                <?php } ?>
                            </select>
                        </div>    
                    </div>
                    <div id="load_endereco">
            <?php
                $responsavel = new ResponsavelModel();
                $sql = $responsavel->buscar($view_sql["id_responsavel"]);
            
            ?>
            <dl class="dl-horizontal">
                <?php foreach($sql as $resp){ 
     
                    $pes = new PessoaModel($resp["id_pessoa"]);
                    $pes_ref = New PessoarefModel();
                   
                    $p = $pes_ref->listarPorPessoa($pes->id_pessoa);
                    $end = new EnderecoModel($p[0]['id_endereco']);
                    $bai = new BairroModel($end->id_bairro);
                    $bairros = $bai->listar();
                    $muni =  new MunicipioModel($bai->id_municipio);
                    $esta = new EstadoModel($muni->id_estado);
                ?>
                <dt>CPF:</dt>
                <dd><?php echo UtilHelper::formataCPF($pes->cpf); ?></dd>
                <dt>Email:</dt>
                <dd><?php echo $pes->email; ?></dd>
                <dt>Endereço:</dt>
                <dd><?php echo $end->endereco .' '.'<strong>Nº: </strong> '.$end->numero. ', <strong>Bairro: </strong>'. $bai->nome; ?></dd>
                <dt>Municipio:</dt>
                <dd><?php echo $muni->nome .' - '. $esta->sigla .', <strong> CEP: </strong> '. UtilHelper::formataCep($end->cep); ?></dd>
                <dt>Click p/ Editar:</dt>
                <dd><button type="button" class="btn btn-default btn-sm" data-toggle="modal" data-target="#editEnd" title="editar"><i class="fa fa-edit"></i></button></dd>
                
                <?php } ?>
            </dl>
            </div>
                    
                    <div class="form-group">
                        <input type="hidden" name="id_aluno" value="<?php echo $view_sql["id_aluno"];?>" />
                        <label for="responsavel" class="col-sm-2 control-label">Aluno:</label>
                        <div class="col-sm-6">
                            <select  class=" form-control" id="responsavel" disabled="">
                                
                               <?php
                               $aluno = new AlunoModel($view_sql["id_aluno"]);
                               $pessoa = new PessoaModel($aluno->id_pessoa);
                               ?>
                                <option value="<?php echo $view_sql["id_aluno"]; ?>"><?php echo $pessoa->nome; ?></option>
                            </select>
                        </div>
                    </div>
                    
                        <div class="form-group">
                    <label for="empresa" class="col-sm-2 control-label">Empresa:</label>
                    <div class="col-sm-6">
                        <select name="id_empresa" class=" form-control" id="load_empresa">
                            <option value="">=> Selecione <=</option>
                          <?php foreach ($view_empr as $empr){
                              $empresa = new EmpresaModel($empr["id_empresa"]);
                              ?>
                              <option value="<?php echo $view_sql["id_empresa"]; ?>"<?php ($view_sql["id_empresa"] == $empr["id_empresa"]) ? print " selected" : print ""; ?>><?php echo $empresa->empresa_nome; ?></option>
                          <?php } ?>
                      </select>
                    </div>
                    </div>   
                    <div id="load_infoempresa"></div>
                    <div class="form-group">
                        <label for="protestotipo" class="col-sm-2 control-label">Especie:</label>
                        <div class="col-sm-6">
                            <select name="id_protesto_tipo" class=" form-control" id="protestotipo">
                                  <option value="">=> Selecione <=</option>
                                <?php foreach ($view_prot as $prot){ ?>
                                    <option value="<?php echo $prot["id_protesto_tipo"]; ?>"<?php ($view_sql["id_protesto_tipo"] == $prot["id_protesto_tipo"]) ? print " selected" : print ""; ?>><?php echo $prot["descricao"]; ?></option>
                                <?php } ?>
                            </select>
                        </div>    
                    </div>
                    <div class="form-group">
                    <label for="id_protesto_status" class="col-sm-2 control-label">Status do Protesto:</label>
                    <div class="col-sm-6">
                        <select name="id_protesto_status" class=" form-control">
                              <option value="">=> Selecione <=</option>
                            <?php foreach ($view_sts as $stt){
                                $status = new ProtestostatusModel($stt['id_protesto_status']);?>
                                <option value="<?php echo $stt["id_protesto_status"]; ?>"<?php ($view_sql["id_protesto_status"] == $stt["id_protesto_status"]) ? print " selected" : print ""; ?>><?php echo $status->descricao; ?></option>
                            <?php } ?>
                        </select>
                    </div>    
                    </div>
                    </div>
                    <div class="col-md-6">
                    <div class="form-group">
                        <label for="numero" class="col-sm-2 control-label">Numero:</label>
                        <div class="col-sm-6">
                            <input type="text"  class="form-control" name="numero" value="<?php echo $view_sql['numero'];?>" placeholder="Ex: 123456...">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="valor_contrato" class="col-sm-2 control-label">Valor do Contrato:</label>
                        <div class="col-sm-6">
                            <div class="input-group">
                            <span class="input-group-addon">R$</span>
                            <input type="text" name="valor_contrato" class="form-control moeda" value="<?php echo UtilHelper::formatoRs($view_sql['valor_contrato']);?>" placeholder="0,00">
                          </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="valor_protesto" class="col-sm-2 control-label">Valor a Protestar:</label>
                        <div class="col-sm-6">
                            <div class="input-group">
                            <span class="input-group-addon">R$</span>
                            <input type="text" name="valor_protesto" class="form-control moeda" value="<?php echo UtilHelper::formatoRs($view_sql['valor_protesto']);?>" placeholder="0,00">
                          </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="data_emissao" class="col-sm-2 control-label">Data de emissão:</label>
                        <div class="col-sm-6">
                            <div class="input-group">
                            <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                            <input type="text" name="data_emissao" class="form-control data calendario" value="<?php echo UtilHelper::formatBr($view_sql['data_emissao']);?>" placeholder="__/__/___">
                          </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="data_vencimento" class="col-sm-2 control-label">Data de Vencimento:</label>
                        <div class="col-sm-6">
                            <div class="input-group">
                            <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                            <input type="text" name="data_vencimento" class="form-control data calendario" value="<?php echo UtilHelper::formatBr($view_sql['data_vencimento']);?>" placeholder="__/__/___">
                          </div>
                        </div>
                    </div>
                        <div class="form-group <?php ($view_erro["ano_base"]) ? print " has-error" : print ""; ?>">
                        <label for="aluno" class="col-sm-2 control-label">Ano do Contrato:</label>
                        <div class="col-sm-6">
                            <select name="ano_base" class="form-control">
                                <option>=> Selecione <=</option>
                                <?php
                                $ano_base = UtilHelper::anos();
                                foreach ($ano_base as $ano){
                                ?>
                                <option value="<?php echo $ano; ?>" <?php ($view_sql["ano_base"] == $ano) ? print " selected" : print ""; ?>><?php echo $ano; ?></option>
                                <?php } ?>
                            </select>
                        </div>
                        <p class="text-red"><?php echo $view_erro['id_aluno'];?></p>
                    </div> 
                    </div>
                </div>
            </div>
        </div>
        </div>   
    </div>
    </section>
</div>
</form>
<div class="modal fade" id="editEnd" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
<div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Editar Informações</h4>
        <div id="mostraTotal" class=""></div>
      </div>
        <form  class="form-horizontal" action="" id="formdata" method="post">
            <div class="modal-body">
            <input type="hidden" name="id_endereco" value="<?php echo $end->id_endereco;?>" />
            <input type="hidden" name="id_pessoa" value="<?php echo $pes->id_pessoa; ?>" />
            <input type="hidden" name="sexo" value="<?php echo $pes->sexo; ?>" />
            <input type="hidden" name="nome" value="<?php echo $pes->nome; ?>" />
            <input type="hidden" name="rg" value="<?php echo $pes->rg; ?>" />
            <input type="hidden" name="id_estado" value="<?php echo $pes->id_estado; ?>" />
            <input type="hidden" name="foto" value="<?php echo $pes->foto; ?>" />
            <div class="form-group ">
                <label for="email" class="col-sm-2 control-label">CPF:</label>
                <div class="col-sm-6">
                    <input type="text" id="cpf" value="<?php echo UtilHelper::formataCPF($pes->cpf); ?>" class="form-control cpf" name="cpf" placeholder="___.___.___-__">
                </div>
            </div>
            <div class="form-group ">
                <label for="email" class="col-sm-2 control-label">Email:</label>
                <div class="col-sm-6">
                    <input type="text" id="email" value="<?php echo $pes->email; ?>" class="form-control" name="email" placeholder="Ex: email@email.com">
                </div>
            </div>

            <div class="form-group ">
                <label for="endereco" class="col-sm-2 control-label">Endereço:</label>
                <div class="col-sm-6">
                    <input type="text" id="endereco" value="<?php echo $end->endereco; ?>" class="form-control" name="endereco" >
                </div>
            </div>
            <div class="form-group ">
                <label for="numero"  class="col-sm-2 control-label">Número:</label>
                <div class="col-sm-6">
                    <input type="text" id="num" value="<?php echo $end->numero; ?>" class="form-control" name="numero" >
                </div>
            </div>
            <div class="form-group ">
                <label for="complemento" class="col-sm-2 control-label">Complemento:</label>
                <div class="col-sm-6">
                    <input type="text" id="complemento" value="<?php echo $end->complemento; ?>" class="form-control" name="complemento" >
                </div>
            </div>
            <div class="form-group ">
                <label for="cep" class="col-sm-2 control-label">CEP:</label>
                <div class="col-sm-6">
                    <input type="text" id="cep" value="<?php echo UtilHelper::formataCep($end->cep); ?>" class="form-control cep" name="cep" >
                </div>
            </div>
            
            <?php
                $municipios = $muni->listar();
            ?>   
            <div class="form-group">
                <label for="id_municipio" class="col-sm-2 control-label">Cidade / Bairro:</label>
                <div class="col-sm-3">
                    <select name="id_municipio" class="form-control" id="buscabairro">
                        <option>=> Selecione <=</option>
                    <?php foreach ($municipios as $mun){
                    $est = new EstadoModel($mun['id_estado']);
                        ?>
                        <option value="<?php echo $mun['id_municipio'];?>" <?php ($bai->id_municipio == $mun['id_municipio']) ? print "selected" : print ''; ?>><?php echo $mun['nome'] .' - '. $est->sigla; ?></option>
                    <?php } ?>
                    </select>
                </div>
                <div class="col-sm-3">
                    <select name="id_bairro" class="form-control" id="carregabairro">
                        <?php
                        $bair = new BairroModel();
                        $lba = $bair->listarPorMunicipio($bai->id_municipio);
                        foreach ($lba as $ba){
                        ?>
                        <option value="<?php echo $ba['id_bairro'];?>" <?php ($bai->id_bairro == $ba['id_bairro']) ? print "selected" : print ''; ?>><?php echo $ba['nome'];?></option>
                        <?php } ?>
                    </select>
                </div>
            </div>
            </div>
            <div class="modal-footer">
                <button type="submit" id="enviaDados" class="btn btn-primary"><i class="fa fa-save"></i></button>
                <a href="/sistema/protesto/editar/id/<?php echo $view_sql['id_protesto'];?>"class="btn btn-danger"><i class="fa fa-close"></i></a>
            </div>
            
        </form>
        <script type="text/javascript">
            $('.cep').mask("99.999-999");
            $('.cpf').mask("999.999.999-99");
            $("#buscabairro").change(function (){
            var municipio = $(this).val();
            if(municipio){
                var url = '/sistema/colaborador/buscarbairro/id/'+municipio;
                $.ajax({
                    type: "POST",
                    url: url,
                    data: {id:municipio},
                    dataType: "html",
                    success: function(data){
                       $("#carregabairro").html(data);
                    }
                });
            }
        });
        
          $("#enviaDados").click(function(){
              
            var email  = $('#email').val();
            var endereco  = $('#endereco').val();
            var cpf  = $('#cpf').val();
            var cep  = $('#cep').val();
            var num  = $('#num').val();
            var buscabairro  = $('#buscabairro option:selected').text();
            var carregabairro  = $('#carregabairro option:selected').text();
            
            var info = $('<dl class="dl-horizontal">\n\
                                <dt>CPF: </dt>\n\
                                <dd>'+ cpf +'</dd>\n\
                                <dt>Email: </dt>\n\
                                <dd>'+ email +'</dd>\n\
                                <dt>Endereco: </dt>\n\
                                <dd>'+ endereco +' <strong>Nº: </strong> '+ num +' <strong>Bairro: </strong>'+ carregabairro +'</dd>\n\
                                <dt>Municipio: </dt>\n\
                                <dd>'+ buscabairro +' <strong> CEP: </strong> '+ cep +'</dd>\n\
                            </dl>');
            
            $('#formdata').submit(function(){
                
                    var dados = $( this ).serialize();

                    $.ajax({
                            type: "POST",
                            url: "/sistema/protesto/editardados",
                            data: dados,
                            success: function( data )
                            {
                                $('#load_endereco').html(info);
                            }
                    });
                $('.modal-backdrop').remove();
                $('.modal').hide();
                return false;
            });
        });
        
        </script>
    </div>
  </div>
  </div>