<form method="post" action="/sistema/protesto/editar/id/<?php echo $view_sql['id_protesto'];?>/" class="form-horizontal" name="form1"  enctype="multipart/form-data" id="form1" runat="server">
<div class="row">
    <section class="col-md-12">
    <div class="nav-tabs-custom">
        <!-- Tabs within a box -->
        <ul class="nav nav-tabs ui-sortable-handle">
          <li id="ab1" class="active"><a href="#aba1" data-toggle="tab">Editar Protesto</a></li>
          <a style="margin: 5px" class="btn btn-default pull-right" href="/sistema/protesto/index/"data-toggle="tooltip" title="Voltar"><i class="fa fa-reply"></i></a>
          <button style="margin: 5px" type="submit" class="btn btn-primary pull-right" data-toggle="tooltip" title="Salvar"><i class="fa fa-save"></i></button>
          
        </ul>
    </div>
    <div class="tab-content no-padding">
        <div class="tab-pane active" id="aba1">
        <div class="box box-info">
            <div class="box-header ui-sortable-handle" >
              <i class="fa fa-envelope"></i>
              <h3 class="box-title">Dados do protesto</h3>
              <!-- tools box -->
              <div class="pull-right box-tools">
                
              </div><!-- /. tools -->
            </div>
            <div class="box-body">
                <div class="row">
                    <div class="col-md-6">
                    <input type="hidden" name="id_protesto" value="<?php echo $view_sql['id_protesto'];?>"/>
                    <div class="form-group">
                        <label for="responsavel" class="col-sm-2 control-label">Responsável:</label>
                        <div class="col-sm-6">
                            <select name="id_responsavel" class=" form-control" id="responsavel" disabled="">
                                <option value="">=> Selecione <=</option>
                                <?php foreach ($view_resp as $resp){ 
                                    $pes =  new PessoaModel($resp['id_pessoa']);
                                ?>
                                <option value="<?php echo $resp["id_responsavel"]; ?>"<?php ($view_sql["id_responsavel"] == $resp["id_responsavel"]) ? print " selected" : print ""; ?>><?php echo $pes->nome; ?></option>
                                <?php } ?>
                            </select>
                        </div>    
                    </div>
                    <div id="load_endereco"></div>
                    
                    <div class="form-group">
                        <label for="responsavel" class="col-sm-2 control-label">Aluno:</label>
                        <div class="col-sm-6">
                            <select name="id_aluno" class=" form-control" id="responsavel" disabled="">
                                
                               <?php
                               $aluno = new AlunoModel($view_sql["id_aluno"]);
                               $pessoa = new PessoaModel($aluno->id_pessoa);
                               ?>
                                <option value="<?php echo $aln["id_aluno"]; ?>"><?php echo $pessoa->nome; ?></option>
                            </select>
                        </div>
                    </div>
                    
                        <div class="form-group">
                    <label for="empresa" class="col-sm-2 control-label">Empresa:</label>
                    <div class="col-sm-6">
                        <select name="id_empresa" class=" form-control" id="load_empresa">
                            <option value="">=> Selecione <=</option>
                          <?php foreach ($view_empr as $empr){
                              $empresa = new EmpresaModel($empr["id_empresa"]);
                              ?>
                              <option value="<?php echo $view_sql["id_empresa"]; ?>"<?php ($view_sql["id_empresa"] == $empr["id_empresa"]) ? print " selected" : print ""; ?>><?php echo $empresa->empresa_nome; ?></option>
                          <?php } ?>
                      </select>
                    </div>
                    </div>   
                    <div id="load_infoempresa"></div>
                    <div class="form-group">
                        <label for="protestotipo" class="col-sm-2 control-label">Especie:</label>
                        <div class="col-sm-6">
                            <select name="id_protesto_tipo" class=" form-control" id="protestotipo">
                                  <option value="">=> Selecione <=</option>
                                <?php foreach ($view_prot as $prot){ ?>
                                    <option value="<?php echo $prot["id_protesto_tipo"]; ?>"<?php ($view_sql["id_protesto_tipo"] == $prot["id_protesto_tipo"]) ? print " selected" : print ""; ?>><?php echo $prot["descricao"]; ?></option>
                                <?php } ?>
                            </select>
                        </div>    
                    </div>
                    <div class="form-group">
                    <label for="id_protesto_status" class="col-sm-2 control-label">Status do Protesto:</label>
                    <div class="col-sm-6">
                        <select name="id_protesto_status" class=" form-control">
                              <option value="">=> Selecione <=</option>
                            <?php foreach ($view_sts as $stt){
                                $status = new ProtestostatusModel($stt['id_protesto_status']);?>
                                <option value="<?php echo $stt["id_protesto_status"]; ?>"<?php ($view_sql["id_protesto_status"] == $stt["id_protesto_status"]) ? print " selected" : print ""; ?>><?php echo $status->descricao; ?></option>
                            <?php } ?>
                        </select>
                    </div>    
                    </div>
                    </div>
                    <div class="col-md-6">
                    <div class="form-group">
                        <label for="numero" class="col-sm-2 control-label">Numero:</label>
                        <div class="col-sm-6">
                            <input type="text"  class="form-control" name="numero" value="<?php echo $view_sql['numero'];?>" placeholder="Ex: 123456...">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="valor_contrato" class="col-sm-2 control-label">Valor do Contrato:</label>
                        <div class="col-sm-6">
                            <div class="input-group">
                            <span class="input-group-addon">R$</span>
                            <input type="text" name="valor_contrato" class="form-control moeda" value="<?php echo UtilHelper::formatoRs($view_sql['valor_contrato']);?>" placeholder="0,00">
                          </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="valor_protesto" class="col-sm-2 control-label">Valor a Protestar:</label>
                        <div class="col-sm-6">
                            <div class="input-group">
                            <span class="input-group-addon">R$</span>
                            <input type="text" name="valor_protesto" class="form-control moeda" value="<?php echo UtilHelper::formatoRs($view_sql['valor_protesto']);?>" placeholder="0,00">
                          </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="data_emissao" class="col-sm-2 control-label">Data de emissão:</label>
                        <div class="col-sm-6">
                            <div class="input-group">
                            <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                            <input type="text" name="data_emissao" class="form-control data calendario" value="<?php echo UtilHelper::formatBr($view_sql['data_emissao']);?>" placeholder="__/__/___">
                          </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="data_vencimento" class="col-sm-2 control-label">Data de Vencimento:</label>
                        <div class="col-sm-6">
                            <div class="input-group">
                            <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                            <input type="text" name="data_vencimento" class="form-control data calendario" value="<?php echo UtilHelper::formatBr($view_sql['data_vencimento']);?>" placeholder="__/__/___">
                          </div>
                        </div>
                    </div>
                        <div class="form-group <?php ($view_erro["ano_base"]) ? print " has-error" : print ""; ?>">
                        <label for="aluno" class="col-sm-2 control-label">Ano do Contrato:</label>
                        <div class="col-sm-6">
                            <select name="ano_base" class="form-control">
                                <option>=> Selecione <=</option>
                                <?php
                                $ano_base = UtilHelper::anos();
                                foreach ($ano_base as $ano){
                                ?>
                                <option value="<?php echo $ano; ?>" <?php ($view_sql["ano_base"] == $ano) ? print " selected" : print ""; ?>><?php echo $ano; ?></option>
                                <?php } ?>
                            </select>
                        </div>
                        <p class="text-red"><?php echo $view_erro['id_aluno'];?></p>
                    </div> 
                    </div>
                </div>
            </div>
        </div>
        </div>   
    </div>
    </section>
</div>
</form>