<?php 
    $col = new ColaboradorModel($_SESSION["colaborador"]);
    $pes = new PessoaModel($col->id_pessoa);
?>
<form method="post" action="/sistema/colaborador/feriasinserir/" class="form-horizontal">
    <div class="row">
        <div class="span6">            
            <ul class="breadcrumb">
                <li><a href="/sistema/index/index/"><i class="fa fa-home"></i> Início</a> <span class="divider">/</span></li>
                <li><a href="/sistema/colaborador/index/"><i class="fa fa-briefcase"></i> Colaborador</a> <span class="divider">/</span></li>
                <li><a href="/sistema/colaborador/ferias/"><i class="fa fa-plane"></i> Férias</a> <span class="divider">/</span></li>
                <li class="active">Inserir</li>
            </ul>
        </div>
        <div class="pull-right">
            <a class="btn" href="/sistema/colaborador/ferias/" title="Voltar"> Voltar <i class="fa fa-reply"></i></a>
        </div>
    </div>
    <div class="well">
    <div class="navbar">
        <div class="span4"><h4>Cadastrar Ferias</h4></div>
        <div class="span4 pull-right">Campos com "<span class="text-error"><i class="fa fa-asterisk"></i></span>" Obrigatorios!</div>
    </div>
        <br /><hr />
        <div class="control-group">
            <label for="chave" class="control-label">Colaborador:</label>
            <div class="controls">
                <input type="text" value="<?php echo $pes->nome; ?>" disabled=""class="span4"/>
                <input type="hidden" name="id_colaborador"  value="<?php echo $col->id_colaborador; ?>"/>
            </div>
        </div>
        <div class="control-group">
            <label for="descricao" class="control-label">Descrição:</label>
            <div class="controls">
                <input type="text" name="descricao" id="descricao" value="" class="span4" required=""/> <span class="text-error">*</span>
            </div>
        </div>
        <div class="control-group">
            <label for="data_inicio" class="control-label">Inicio de Ferias:</label>
            <div class="controls">
                <div class="input-append">
                    <input type="text" name="data_inicio" id="data_inicio" value="" class="span2 calendario" required=""/> 
                    <span class="add-on"><i class="fa fa-calendar"></i></span>
                </div> <span class="text-error">*</span>
            </div>
        </div>
        <div class="control-group">
            <label for="data_fim" class="control-label">Termino de Férias:</label>
            <div class="controls">
                <div class="input-append">
                    <input type="text" name="data_fim" id="data_fim" value="" class="span2 calendario" required=""/>
                    <span class="add-on"><i class="fa fa-calendar"></i></span>
                </div> <span class="text-error">*</span>
            </div>
        </div>
        <div class="control-group">
            <label for="data_fim" class="control-label"></label>
            <div class="controls">
                <button type="submit" class="btn btn-primary">Salvar <i class="fa fa-save"></i></button>
                <button type="reset" class="btn btn-danger">Limpar <i class="fa fa-trash-o"></i></button>
            </div>
        </div>
        
            
</div>
</form>