<form method="post" action="/sistema/colaborador/inserir/" class="form-horizontal" name="form1" enctype="multipart/form-data" id="form1" runat="server">
<div class="row">
    <div class="span5">            
        <ul class="breadcrumb">
            <li><a href="/sistema/index/index/"><i class="fa fa-home"></i> Início</a> <span class="divider">/</span></li>
            <li><a href="/sistema/colaborador/index/"><i class="fa fa-briefcase"></i> Colaborador</a> <span class="divider">/</span></li>
            <li class="active">Cadastro</li>
        </ul>
    </div>
    <div class="pull-right">
        <a class="btn" href="/sistema/colaborador/index/" title="Voltar"><i class="fa fa-reply"></i> Voltar</a>
    </div>
</div>
<div class="well">
  <legend>Dados do colaborador <div class="span4 pull-right" style="font-size: 14px;">Campos com "<span class="text-error"><i class="fa fa-asterisk"></i></span>" Obrigatorios!</div></legend>
    <div class="control-group">
    <label for="Tipo" class="control-label">Tipo:</label> 
    <div class="controls"> 
        <select name="id_colaborador_tipo" required=""> 
            <option value="">=> Selecione <=</option> 
            <?php foreach ($view_ftp as $ftp){ ?>
                <option value="<?php echo $ftp["id_colaborador_tipo"]; ?>"><?php echo $ftp["descricao"]; ?></option>
            <?php } ?>
        </select> <span class="text-error">*</span>
    </div>
</div>
<div class="control-group" id="ftipo">
    <label for="id_orientador" class="control-label">Orientador:</label>
    <div class="controls">
        <div class="input-append">
            <input type="hidden" name="id_orientador" id="id_orientador" />
            <input class="span5 " id="show_id_orientador" type="text" required="" disabled=""> 
            <a href="#myModal" role="button" class="btn btn-info" data-toggle="modal"><i class="fa fa-plus-square-o"></i></a>
        </div> <span class="text-error">*</span>
    </div>
</div>
</div>
<div class="well">
    <legend>Dados Pessoais <div class="span4 pull-right" style="font-size: 14px;">Campos com "<span class="text-error"><i class="fa fa-asterisk"></i></span>" Obrigatorios!</div></legend>
    <div class="control-group">
        <label for="foto" class="control-label">Foto:</label>
        <div class="controls">
            <img id="blah" class="img-circle" src="/sistema/public/img/user-default.png" alt="" style="width: 100px" />
            <input type='file' id="imgInp" name="foto"/>
        </div>
    </div> 
    <div class="control-group">
        <label for="nome" class="control-label">Nome Completo:</label>
        <div class="controls">
            <input type="text" name="nome" id="nome" value="" class="span5" /> <span class="text-error">*</span>
        </div>
    </div>
    <div class="control-group">
        <label for="principal" class="control-label">Sexo:</label>
        <div class="controls">
            <label class="radio">
            <input type="radio" name="sexo" id="principal" size="5" value="M" />
            Masculino.
            </label>
            <label class="radio">
            <input type="radio" name="sexo" id="principal" size="5" value="F" /> 
            Feminino.
            </label>
        </div> 
    </div>
    <div class="control-group">
        <label for="pai" class="control-label">Nome do Pai:</label>
        <div class="controls">
            <input type="text" name="pai" id="pai" value="" class="span5" />
        </div>
    </div>
    <div class="control-group">
        <label for="mae" class="control-label">Nome da Mãe:</label>
        <div class="controls">
            <input type="text" name="mae" id="mae" value="" class="span5" />
        </div>
    </div>
    <div class="control-group">
        <label for="profissao" class="control-label">Profissão:</label>
        <div class="controls">
            <input type="text" name="profissao" id="profissao" value="" class="span5" />
        </div>
    </div>
    <div class="control-group">
        <label for="data_nascimento" class="control-label">Data de Nascimento:</label>
        <div class="controls">
            <div class="input-append">
                <input type="text" name="data_nascimento" id="data_nascimento" value="" class="span2 calendario data" placeholder="__/__/____" required=""/> <span class="text-error">*</span>
                <span class="add-on"><i class="fa fa-calendar"></i></span>
            </div> <span class="text-error">*</span>
        </div>
    </div>
    <div class="control-group">
        <label for="nacionalidade" class="control-label">Nacionalidade:</label> 
        <div class="controls">
            <input type="text" name="nacionalidade" id="nacionalidade" value="" class="span5" required=""/> <span class="text-error">*</span>
        </div>
    </div>
    <div class="control-group">
        <label for="naturalidade" class="control-label">Naturalidade:</label>
        <div class="controls">
            <input type="text" name="naturalidade" id="naturalidade" value="" class="span5" required=""/> <span class="text-error">*</span>
        </div>
    </div>
    <div class="control-group">
        <label for="cpf" class="control-label">cpf:</label>
        <div class="controls">
            <input type="text" name="cpf" class="cpf" maxlength="14" class="cpf span2" placeholder="___.___.___-__" required=""> <span class="text-error">*</span>
        </div>
    </div>
    <div class="control-group">
        <label for="rg" class="control-label">Rg:</label>
        <div class="controls">
            <input type="text" name="rg" id="rg" value="" class="span2" required="" /> <span class="text-error">*</span>
            Órgão Expedidor:
            <input type="text" name="expedidor" id="expedidor" value="" class="span2" required=""/> <span class="text-error">*</span>
        </div>     
    </div>
    <div class="control-group">
        <label for="rg" class="control-label">Data de Expedição::</label>
        <div class="controls">
            <div class="input-append">
                <input type="text" placeholder="__/__/____" name="data_expedicao" id="data_expedicao" value="" class="span2 calendario data"  required=""/> <span class="text-error">*</span>
                <span class="add-on"><i class="fa fa-calendar"></i></span>
            </div> <span class="text-error">*</span>
            
            UF:
            <select name="id_estado" class="span2" required="">
                <option value="">=> Selecione <=</option>
                <?php foreach ($view_est as $est){ ?>
                    <option value="<?php echo $est["id_estado"]; ?>"><?php echo $est["sigla"]; ?></option>
                <?php } ?>
            </select> <span class="text-error">*</span>
        </div>     
    </div>
    <div class="control-group">
        <label for="pis" class="control-label">PIS:</label>
        <div class="controls">
            <input type="text" name="pis" id="pis" value="" class="span3" />
        </div>
    </div>
    <div class="control-group">
        <label for="estado_civil" class="control-label">Estado Civil:</label>
        <div class="controls">
            <input type="text" name="estado_civil" id="estado_civil" value="" class="span2" required=""/> <span class="text-error">*</span>    
        </div>
    </div>
    <div class="control-group">
        <label for="email" class="control-label">Email:</label>
        <div class="controls">
            <input type="email" name="email" id="chave" value="" class="span5" required=""/> <span class="text-error">*</span>
        </div>
    </div>
</div>
<div class="well">
    <div class="navbar">
        <div class="span4"><h4>Endereço do Colaborador</h4></div>
    </div>
    <br /><hr />
    <div class="control-group">
        <label for="endereco" class="control-label">Endereço:</label>
        <div class="controls">
            <input type="text" name="endereco" id="endereco" value="" class="span5" /> <span class="text-error">*</span>
            Nº:
            <input type="text" name="numero" id="numero" value="" class="span1" /> <span class="text-error">*</span>
        </div>
    </div>
    <div class="control-group">
        <label for="municipio" class="control-label">Municipio:</label>
        <div class="controls">
            <select name="id_municipio" class="span2" id="municipio" required="">
                    <option value="">=> Selecione <=</option>
                <?php foreach ($view_mun as $mun){ ?>
                    <option value="<?php echo $mun["id_municipio"]; ?>"><?php echo $mun["nome"]; ?></option>
                <?php } ?>
            </select> <span class="text-error">*</span>
            Bairro:

            <select name="id_bairro" class="span2" id="load_bairro">
                <option value="">Selecione o Bairro</option>
            </select>

        </div>
    </div>
    <div class="control-group">
        <label for="cep" class="control-label">CEP:</label>
        <div class="controls">
            <input type="text" name="cep" id="cep" value="" class="span2 cep"   maxlength="10" placeholder="__.___-___"/>
        </div>
    </div>
    <div class="control-group">
        <label for="complemento" class="control-label">Complemento:</label>
        <div class="controls">
            <input type="text" name="complemento" id="complemento" value="" class="span5" placeholder="Ex.: Bloco A." />
        </div>
    </div>
    <div class="control-group">
        <label for="telefone" class="control-label">Telefone:</label>
        <div class="controls">
            <input type="text" name="telefone" id="telefone" value="" class="span5 telefone" onKeyPress="MascaraTelefone(form1.telefone);"  maxlength="14" placeholder="(__) ___-____"/>
        </div>
    </div>
</div>
<div class="well">
    <div class="navbar">
        <div class="span4"><h4>Dados Bancários do Colaborador</h4></div>
    </div>
    <br /><hr />
    <div class="control-group">
        <label for="banco" class="control-label">Banco:</label>
        <div class="controls">
            <input type="text" name="banco" id="banco" value="" class="span3" required=""/> <span class="text-error">*</span>
            Agencia:
            <input type="text" name="agencia" id="agencia" value="" class="span1" required=""/> <span class="text-error">*</span>
            Conta Corrente:
            <input type="text" name="conta" id="conta" value="" class="span2" required=""/> <span class="text-error">*</span>
        </div>
    </div>
</div>
<div class="well">
    <div class="navbar">
        <div class="span4"><h4>Dados Escolares do Colaborador</h4></div>
    </div>
    <br /><hr />
    <div class="control-group">
        <label for="instiuicao" class="control-label">Instituição De Origem:</label>
        <div class="controls">
            <select name="id_instituicao" id="instituicao">
                    <option value="">=> Selecione <=</option>
                <?php foreach ($view_ins as $ins){ ?>
                    <option value="<?php echo $ins["id_instituicao"]; ?>"><?php echo $ins["nome"]; ?></option>
                <?php } ?>
            </select>
        </div>
    </div>
    <div class="control-group">
        <label for="curso" class="control-label" id="load_instituicao">Curso:</label>
        <div class="controls">
            <select name="id_curso" id="load_curso">
                    <option value="">=> Selecione <=</option>
            </select>
        </div>
    </div>
    <div class="control-group">
        <label for="semestre" class="control-label">Semestre:</label>
        <div class="controls">
            <input type="text" name="semestre" id="semestre" value="" class="span2 semestre" placeholder="____._" required=""/>
        </div>
    </div>
    <div class="control-group">
        <label for="data_inicio" class="control-label">Inicio de Curso:</label>
        <div class="controls">
            <input type="text" name="data_inicio" id="data_inicio " value="" class="span2 calendario data" placeholder="__/__/___" required=""/>
        </div>
    </div>
    <div class="control-group">
        <label for="data_fim" class="control-label">Termino de Curso:</label>
        <div class="controls">
            <input type="text" name="data_fim" id="data_fim" value="" class="span2 calendario data" placeholder="__/__/___" required=""/>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label"></label>
        <div class="controls">
            <button type="submit" class="btn btn-primary">Salvar <i class="fa fa-save"></i></button>
            <button type="reset" class="btn btn-danger">Limpar <i class="fa fa-trash-o"></i></button>
        </div>
    </div>
</div>


 
<!-- Modal -->
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Pessoa Orientador</h3>
  </div>
  <div class="modal-body">
    <div class="control-group">
        <label for="pesquisar" class="control-label">Pesquisar:</label>
        <div class="controls">
              <input type="text" name="pesquisar" id="pesquisar" value="" placeholder="Pesquisar nome" />
        </div>
    </div>
      <table class="table table-bordered">
          <tr class="titulo2">
              <th></th>
              <th>ID</th>
              <th>Nome</th>
              <th>CPF</th>
              <th>RG</th>
          </tr>
          <?php foreach ($view_ori as $ori){
              $pes =  new PessoaModel($ori["id_pessoa"]);
          ?>
          <tr>
              <td><input type="radio" value="<?php echo $ori["id_orientador"]; ?>" name="orientador" class="modal_id_orientador" title="<?php echo $pes->nome; ?>"  /></td>
              <td><span class="badge badge-inverse"><?php echo $ori["id_orientador"]; ?></span></td>
              <td><?php echo $pes->nome; ?></td>
              <td><?php echo $pes->cpf; ?></td>
              <td><?php echo $ori['matricula']; ?></td>
          </tr>
          <?php }?>
      </table>
  </div>
  <div class="modal-footer">
    <button class="btn btn-danger" data-dismiss="modal" aria-hidden="true">Cancelar</button>
    <button class="btn btn-primary" id="modal_btn_salvar">Salvar</button>
  </div>
</div>
</form>

