<div class="row">
<div class="span5">            
<ul class="breadcrumb">
  <li><a href="/sistema/index/index/"><i class="fa fa-home"></i> Início</a> <span class="divider">/</span></li>
  <li class="active"><i class="fa fa-share-alt-square"></i> Area de Atuação</li>
</ul>
</div>
<div class="pull-right">
    <a class="btn" href="/sistema/areaatuacao/inserir/" title="Adicionar"><i class="fa fa-plus-circle"></i> Novo</a>
    <a class="btn" href="/sistema/index/index/" title="Voltar"><i class="fa fa-reply"></i> Voltar</a>
</div>
</div>
    <table class="table table-bordered">
        <tbody>
            <tr class="titulo2">
                <th>ID</th>
                <th>Descrição</th>
                <th>Chave</th>
                <th>Operações</th>
            </tr>
            <?php foreach ($view_sql as $sql){?>
            <tr class="item2">
                <td><span class="badge badge-inverse"><?php echo $sql['id_area_atuacao'];?></span></td>
                <td><?php echo $sql['descricao'];?></td>
                <td><?php echo $sql['chave'];?></td>
                <td>
                    <div class="btn-group">
                        <a class="btn btn-success btn-small" href="<?php echo "/sistema/areaatuacao/visualizar/id/{$sql["id_area_atuacao"]}";?>" title="Visualizar"><i class="fa fa-search"></i></a>
                        <a class="btn btn-warning btn-small" href="<?php echo "/sistema/areaatuacao/editar/id/{$sql["id_area_atuacao"]}";?>" title="Editar"><i class="fa fa-edit"></i></a>
                        <a href="#id<?php echo "{$sql["id_area_atuacao"]}";?>" role="button" class="btn btn-danger btn-small" data-toggle="modal"><i class="fa fa-trash-o"></i></a>
                    </div>
                </td>
            </tr>
            <?php } ?>
    </tbody>
</table>
<?php foreach ($view_sql as $sql){ ?>
<div id="id<?php echo "{$sql["id_area_atuacao"]}";?>" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Deseja Realmente Apagar?</h3>
  </div>
  <div class="modal-body">
      <p>O registro será apagado permanente!</p>
  </div>
  <div class="modal-footer">
      <a class="btn btn-danger" href="<?php echo "/sistema/areaatuacao/excluir/id/{$sql["id_area_atuacao"]}";?>" title="Excluir">Sim</a>
      <button class="btn btn-info" data-dismiss="modal" aria-hidden="true">Cancelar</button>
    
  </div>
</div>
<?php } ?>
